.travis.yml
Makefile
glide.lock
glide.yaml

chore(project): add support for CI builds on travis-ci

---

parser/asciidoc-grammar.peg
parser/asciidoc_parser_test.go
parser/quotedtext_test.go
renderer/html5/html5_renderer.go
renderer/html5/html5_renderer_test.go

feat(rendering): render italic and monospace quotes

---

glide.lock
parser/asciidoc-grammar.peg
parser/asciidoc_parser_test.go
parser/blank_line_test.go
parser/block_image_test.go
parser/delimited_block_test.go
parser/external_link_test.go
parser/heading_test.go
parser/list_test.go
parser/meta_elements_test.go
parser/paragraph_test.go
parser/quoted_text_test.go
renderer/html5/blank_line_test.go
renderer/html5/renderer.go
test/log_init.go
types/types.go

fix(parser): parse blank lines

---

parser/asciidoc-grammar.peg
parser/asciidoc_parser_test.go
parser/block_image_test.go
parser/meta_elements_test.go
parser/paragraph_test.go
renderer/html5/image.go
renderer/html5/paragraph.go
renderer/html5/paragraph_test.go
renderer/html5/renderer.go
types/types.go

feat(parser): allow id and title on paragraphs

---

renderer/html5/renderer.go
renderer/html5/section.go
renderer/options.go
types/grammar_types.go
types/type_utils.go

chore(project): replace 'reflect.TypeOf()' with '%T' in fmt.Printf() statements

---

.travis.yml

chore(project): also build with Go 1.9 on travis-ci

---

.travis.yml

chore(project): build on the latest versions of golang

---

.travis.yml

chore(project): include coverage reports with codecov

---

.gitignore
Makefile
README.adoc

chore(project): include all packages during test coverage

---

.travis.yml

chore(project): build from 'tip' instead of 'master' on travis-ci

---

CONTRIBUTE.adoc
README.adoc

docs(project): update README and include CONTRIBUTE

---

.travis.yml

chore(project): allow build failure on 'go:tip' version

---

glide.lock
glide.yaml
libasciidoc.go
libasciidoc_test.go
parser/asciidoc_parser_test.go
parser/document_attributes_test.go
parser/section_test.go
renderer/html5/document.go
renderer/html5/document_header.go
renderer/html5/document_test.go
renderer/html5/renderer.go
renderer/html5/renderer_test.go
types/document_attributes.go
types/grammar_types.go

refactor(types/renderer): render document title

---

README.adoc
README.html
parser/asciidoc-grammar.peg
parser/asciidoc_parser.go
parser/quoted_text_test.go
renderer/html5/quoted_text_test.go
types/grammar_types.go
types/type_utils.go

feat(parser): support substitution prevention

---

renderer/html5/document.go
renderer/html5/document_details.go
renderer/html5/document_details_test.go
renderer/html5/table_of_content.go
renderer/html5/table_of_content_test.go
types/document_attributes.go

includes support for custom levels

feat(renderer): render table of content

---

types/grammar_types.go
types/grammar_types_utils.go

chore(project): remove unused methods on grammar types

---

types/grammar_types.go

chore(project): remove dead code

---

renderer/html5/external_link.go
renderer/html5/external_link_test.go

feat(renderer): render external links without description

---

parser/asciidoc-grammar.peg
parser/asciidoc_parser.go
parser/external_link_test.go
renderer/html5/external_link.go
renderer/html5/external_link_test.go
renderer/html5/renderer.go
types/grammar_types.go

also: rename `ExternalLink` to `Link`.
Fixes #56

feat(parser): support relative links

---

parser/asciidoc-grammar.peg
parser/asciidoc_parser.go
parser/image_test.go
parser/section_test.go
renderer/html5/table_of_content_test.go
types/grammar_types.go
types/grammar_types_utils.go

Section link

---

.travis.yml
appveyor.yml

chore(project): build with Golang 1.10 on Travis-ci (#68)

---

parser/asciidoc-grammar.peg
parser/asciidoc_parser.go
parser/delimited_block_test.go
parser/labeled_list_test.go
parser/unordered_list_test.go
renderer/html5/delimited_block.go
renderer/html5/delimited_block_test.go
types/grammar_types.go

feat(parser/renderer): support example blocks

---

parser/asciidoc-grammar.peg
parser/asciidoc_parser.go
parser/delimited_block_test.go
parser/element_attributes_test.go
parser/image_test.go
parser/labeled_list_test.go
parser/ordered_list_test.go
parser/unordered_list_test.go
renderer/html5/external_link.go
renderer/html5/ordered_list.go
renderer/html5/ordered_list_test.go
renderer/html5/renderer.go
renderer/html5/unordered_list.go
renderer/html5/unordered_list_test.go
types/document_attributes.go
types/grammar_types.go
types/grammar_types_test.go
types/grammar_types_utils.go

feat(parser/renderer): support ordered lists

---

renderer/context.go

From megacheck: infinite recursive call (SA5007)

Fix infinite recursive call

---

CONTRIBUTE.adoc

Reference AngularJS commit message conventions.  Clean up grammar,
punctuation, and whitespace.

docs(project): update CONTRIBUTE

---

parser/asciidoc-grammar.peg
parser/asciidoc_parser.go
parser/delimited_block_test.go

support unclosed blocks if they reach end of file
fixes #101:

fix(parser): support unclosed delimited blocks (#101)

---

README.adoc

docs(project): add go report card in README (#110)

---

.gitignore

Also, add `*.test` in `.gitignore` to avoid
repeating the same mistake again.
Fixes #130

fix(project): remove `.test` files

---

pkg/parser/section_test.go
pkg/renderer/html5/document.go
pkg/renderer/html5/document_test.go
pkg/renderer/html5/section_test.go
pkg/types/grammar_types.go
pkg/types/grammar_types_utils_test.go
pkg/types/non_alphanumerics_replacement.go

fix(renderer): element IDs and document header

---

Makefile

fix(build): use optimized grammar when building/installing

---

.travis.yml
pkg/parser/bench_test.go

using environment variable to use a 10x factor on timeouts
fixes #162

fix(parser): increase bench timeout on Travis-ci

---

README.adoc

docs(project): include support for tables in README.adoc

---

pkg/renderer/context.go
pkg/renderer/html5/table.go
pkg/renderer/html5/table_test.go

fix(renderer): fix table numbering when title is included (#166)

---

pkg/parser/comment_test.go
pkg/parser/delimited_block_test.go
pkg/parser/document_attributes_test.go
pkg/parser/inline_elements_test.go
pkg/parser/labeled_list_test.go
pkg/parser/paragraph_test.go
pkg/parser/passthrough_test.go
pkg/parser/quoted_text_test.go
pkg/parser/section_test.go
pkg/parser/table_test.go
pkg/parser/unordered_list_test.go
pkg/renderer/html5/delimited_block.go
pkg/renderer/html5/quoted_text.go
pkg/types/grammar_types.go
pkg/types/grammar_types_utils_test.go

refactor(types): move quoted text kind in attributes

---

pkg/renderer/html5/paragraph_test.go
pkg/renderer/html5/passthrough_test.go
pkg/renderer/html5/string.go
pkg/renderer/html5/string_test.go
pkg/renderer/html5/table_of_contents_test.go

replace `...` sequence with `&#8230;&#8203;`
fixes #175

feat(renderer): convert ellipsis

---

cmd/libasciidoc/root_cmd_test.go
libasciidoc_test.go
pkg/parser/asciidoc_parser_test.go
pkg/renderer/html5/document.go
pkg/renderer/html5/renderer_test.go
pkg/types/document_attributes.go
pkg/types/grammar_types.go
pkg/types/non_alphanumerics_replacement.go

chore(project): address problems reported by golangci

---

libasciidoc_test.go
pkg/renderer/html5/document.go
pkg/renderer/html5/document_details_test.go
pkg/renderer/html5/document_test.go

fix(renderer): missing '</head>' tag

---

pkg/parser/delimited_block_test.go
pkg/parser/labeled_list_test.go
pkg/parser/ordered_list_test.go
pkg/parser/unordered_list_test.go
pkg/renderer/html5/ordered_list_test.go
pkg/types/grammar_types.go
pkg/types/grammar_types_test.go

List items were parsed but not "attached" to their
parent item
fixes #203

fix(parser): missing sublists

---

pkg/parser/delimited_block_test.go
pkg/renderer/context.go
pkg/renderer/html5/delimited_block.go
pkg/renderer/html5/delimited_block_test.go
pkg/renderer/html5/labeled_list_test.go

feat(renderer): support ID and title on delimited blocks

---

pkg/renderer/html5/delimited_block.go
pkg/renderer/html5/delimited_block_test.go
pkg/renderer/html5/document.go
pkg/renderer/html5/document_details.go
pkg/renderer/html5/paragraph.go
pkg/types/document_attributes.go

also on admonition paragraphs
fixes #214

feat(renderer): support icons in admonition blocks

---

.travis.yml
Makefile

Add linters target to run gofmt and golint checks against codebase.
Fixes #61

feat(make): add linters target (#61)

---

cmd/libasciidoc/main.go
pkg/parser/delimited_block_test.go
pkg/renderer/html5/delimited_block_test.go
pkg/types/document_attributes.go
pkg/types/grammar_types.go

See individual commits for more details.
Fixes #219

chore(project): Fix errors reported by GolangCI (#219)

---

Makefile
README.adoc

docs(project): update installation instructions

---

.travis.yml
appveyor.yml

fix(build): remove support for golang1.8 on travis-ci and appveyor

---

Gopkg.toml

chore(project): use default URL for sirupsen/logrus

---

pkg/parser/asciidoc-grammar.peg
pkg/parser/asciidoc_parser.go
pkg/parser/image_test.go
pkg/renderer/html5/image.go
pkg/renderer/html5/renderer.go
pkg/types/grammar_types.go

refactor(types): rename `BlockImage` to `ImageBlock`

---

codecov.yml

include token in config file
fixes #252

chore(project): re-enable codecov

---

pkg/renderer/html5/table_of_contents.go
pkg/renderer/html5/table_of_contents_test.go

fix(renderer): fix panic in ToC when doc has no section

---

pkg/parser/asciidoc-grammar.peg
pkg/parser/cross_reference_test.go
pkg/parser/delimited_block_test.go
pkg/parser/document_attributes_test.go
pkg/parser/element_attributes_test.go
pkg/parser/footnote_test.go
pkg/parser/image_test.go
pkg/parser/literal_block_test.go
pkg/parser/paragraph_test.go
pkg/parser/section_test.go
pkg/parser/table_of_contents_test.go
pkg/parser/unordered_list_test.go
pkg/renderer/html5/delimited_block.go
pkg/renderer/html5/element_id.go
pkg/renderer/html5/element_id_test.go
pkg/renderer/html5/labeled_list.go
pkg/renderer/html5/literal_blocks.go
pkg/renderer/html5/ordered_list.go
pkg/renderer/html5/paragraph.go
pkg/renderer/html5/section.go
pkg/renderer/html5/section_test.go
pkg/renderer/html5/table_of_contents.go
pkg/renderer/html5/unordered_list.go
pkg/types/element_attributes.go
pkg/types/grammar_types.go
pkg/types/grammar_types_utils_test.go
pkg/types/non_alphanumerics_replacement.go

feat(parser/renderer): support element ID prefix

---

.gitignore
.golangci.yml
pkg/renderer/file_inclusions.go
pkg/renderer/html5/delimited_block_test.go
pkg/renderer/html5/file_inclusion_test.go
pkg/renderer/html5/includes/hello_world.go
pkg/renderer/html5/includes/sample.html

feat(renderer): support file inclusion of non asciidoc files

---

.golangci.yml
pkg/parser/inline_elements_test.go
pkg/renderer/html5/attribution.go
pkg/renderer/html5/delimited_block.go
pkg/renderer/html5/document.go
pkg/renderer/html5/document_details.go
pkg/renderer/html5/external_link.go
pkg/renderer/html5/paragraph.go
pkg/renderer/html5/quoted_text.go
pkg/renderer/html5/renderer.go
pkg/renderer/html5/string.go
pkg/renderer/html5/table_of_contents.go
pkg/types/grammar_types.go
pkg/types/grammar_types_utils.go
pkg/types/non_alphanumerics_replacement.go

- remove unused/dead code
- reduce cyclo complexity
- refactor functions
- fix spelling
- add 'nolint' comments where appropriate
Fixes #328

chore(project): clean-up of code

---

pkg/renderer/file_inclusion_test.go
pkg/renderer/html5/file_inclusion_test.go

chore(renderer): add tests to verify support for multiple file inclusions

---

pkg/parser/asciidoc-grammar.peg
pkg/parser/passthrough_test.go
pkg/parser/quoted_text_test.go
pkg/renderer/html5/quoted_text_test.go
pkg/types/grammar_types.go

fix(parser): fix parsing in quoted text

---

pkg/parser/asciidoc-grammar.peg

fix(parser): invalid grammar rule

---

pkg/parser/comment_test.go
pkg/parser/document_processing.go
pkg/parser/element_attributes_test.go
pkg/parser/mixed_lists_test.go
pkg/parser/ordered_list_test.go
pkg/types/grammar_types.go

refactor(parser): remove 'Position' field in OrderedListItem

---

pkg/parser/asciidoc-grammar.peg
pkg/parser/asciidoc_parser.go
pkg/parser/delimited_block_test.go
pkg/parser/link_test.go
pkg/renderer/html5/delimited_block_test.go
pkg/renderer/html5/external_link_test.go

stop parsing the location if an EOL is found
fixes #368

fix(parser): external link without brackets

---

pkg/parser/bench_test.go
test/bench/vertx-examples.adoc

add the `verts-examples.adoc` file from
https://github.com/vert-x3/vertx-examples/blob/master/core-examples/README.adoc
and run the parser 50x

chore(parser): add benchmark with real-world doc

---

pkg/parser/asciidoc-grammar.peg
pkg/parser/asciidoc_parser.go
pkg/parser/bench_test.go
pkg/parser/image_test.go
pkg/parser/paragraph_test.go
pkg/parser/quoted_text_test.go
pkg/types/grammar_types.go

also, simplify the grammar for parsing image atrributes
fixes #352

refactor(parser): remove empty attributes in images

---

CONTRIBUTE.adoc
pkg/parser/bench_test.go

Convert to standard Go benchmarks

---

pkg/parser/asciidoc-grammar.peg
pkg/parser/asciidoc_parser.go
pkg/parser/inline_elements_test.go

refactor(parser): use character class matcher

---

Makefile

chore(makefile): fix typo

---

pkg/parser/asciidoc_parser.go

reverting to `master` version of mna/pigeon while https://github.com/mna/pigeon/pull/86 is discussed.

chore(parser): generate parser with 'master' of mna/pigeon

---

Makefile
pkg/parser/document_preprocessing.go
pkg/parser/file_inclusion_test.go
pkg/parser/includes/hello_world_tags.go
pkg/parser/includes/tag-include.adoc
pkg/parser/parser.go
pkg/parser/parser.peg
pkg/renderer/html5/file_inclusion_test.go
pkg/renderer/html5/includes/tag-include.adoc
pkg/types/element_attributes.go
pkg/types/types.go

feat(parser): support file inclusion with tag ranges

---

pkg/parser/document_processing.go
pkg/renderer/html5/html5.go
pkg/types/document_xrefs.go
pkg/types/element_attributes.go
pkg/types/types.go

chore(project): remove unused code

---

.travis.yml
appveyor.yml
testsupport/log_init.go

Drop support for Go 1.10.x
Fixes #400

build(project): build with Go 1.13

---

pkg/parser/file_inclusion.go
pkg/parser/file_inclusion_test.go
pkg/renderer/html5/file_inclusion_test.go
pkg/types/types.go

include the line number of the start tag in the error message
Fixes #392

feat(parser): report error on unbalanced/unclosed tag

---

pkg/renderer/html5/paragraph.go
pkg/renderer/html5/paragraph_test.go

feat(renderer): add role as CSS class in paragraphs

---

pkg/renderer/html5/delimited_block.go
pkg/renderer/html5/delimited_block_test.go

fix(renderer): do not highlight syntax when language is not set

---

libasciidoc_test.go
pkg/parser/cross_reference_test.go
pkg/parser/document_attributes_test.go
pkg/parser/document_processing.go
pkg/parser/document_processing_test.go
pkg/parser/image_test.go
pkg/parser/link_test.go
pkg/parser/section_test.go
pkg/renderer/html5/delimited_block.go
pkg/renderer/html5/delimited_block_test.go
pkg/types/document_attributes.go
pkg/types/document_attributes_test.go
pkg/types/element_attributes.go
pkg/types/predefined_attributes.go
pkg/types/predefined_attributes_test.go
testsupport/parse_document.go
testsupport/render_html5.go

Adding test to verify that custom attributes
passed in the configuration work as expected
Updates #509

test(parser): verify configuration attributes

---

libasciidoc.go
pkg/parser/document_processing_rearrange_lists_test.go
pkg/renderer/context.go
pkg/renderer/html5/article_adoc_test.go
pkg/renderer/html5/blank_line.go
pkg/renderer/html5/cross_reference.go
pkg/renderer/html5/delimited_block.go
pkg/renderer/html5/document_details.go
pkg/renderer/html5/elements.go
pkg/renderer/html5/footnote.go
pkg/renderer/html5/html5.go
pkg/renderer/html5/index_term.go
pkg/renderer/html5/paragraph.go
pkg/renderer/html5/section.go
pkg/renderer/html5/table_of_contents.go
testsupport/table_of_contents.go

refactor(renderer): extract document from rendering context

---

pkg/parser/document_processing_rearrange_sections.go
pkg/parser/footnote_test.go
pkg/parser/parser.go
pkg/parser/parser.peg
pkg/renderer/html5/footnote_test.go
pkg/types/types.go

grammar for footnote references was invalid
Fixes #532

fix(parser): fix footnotes grammar

---

CHANGELOG.md

update CHANGELOG.md for v0.4.0.

---

pkg/parser/document_processing_rearrange_lists_test.go
pkg/parser/icon_test.go
pkg/parser/labeled_list_test.go
pkg/parser/parser.go
pkg/parser/parser.peg
pkg/renderer/sgml/html5/icon_test.go

This PR is based upon the work for icons (PR #613).  Only the last commit here is relevant.

fix support for : (and inline images, icons) in definition list terms

---

pkg/parser/paragraph_test.go
pkg/parser/parser.go
pkg/parser/parser.peg
pkg/renderer/sgml/blank_line.go
pkg/renderer/sgml/elements.go
pkg/renderer/sgml/html5/paragraph.go
pkg/renderer/sgml/html5/paragraph_test.go
pkg/renderer/sgml/html5/templates.go
pkg/renderer/sgml/sgml_renderer.go
pkg/renderer/sgml/templates.go
pkg/renderer/sgml/xhtml5/blank_line_test.go
pkg/renderer/sgml/xhtml5/paragraph.go
pkg/renderer/sgml/xhtml5/templates.go
pkg/types/types.go

This PR is based on PR #636 and contains it's commit.  It should be merged after wards (only the final commit).

Support for thematic break elements

---

pkg/renderer/sgml/html5/image.go
pkg/renderer/sgml/image.go
pkg/renderer/sgml/xhtml5/image.go

refactor(renderer): "Figure" prefix for images in template

---

.github/workflows/ci-build.yml

chore(build): Use https://github.com/golangci/golangci-lint-action

---

pkg/parser/parser.go
pkg/parser/parser.peg
pkg/parser/quoted_text_test.go
pkg/renderer/sgml/html5/quoted_text_test.go
pkg/renderer/sgml/xhtml5/quoted_text_test.go
pkg/types/attributes.go
pkg/types/types.go

This refactors the handling of these to be more consistent,
in order to support future work to use more flexible (and
compliant with asciidoctor) attributes. This leads into the
fixes for making roles work everywhere, as well as providing
richer attributes for Table options.

refactor(parser): Quoted Text Attribute refactoring

---

LIMITATIONS.adoc
README.adoc

This adds a lot more detail covering what is supported and
what is not to the documentation files.
There might be missing items still, but I've tried to cover
everything we know about.
Fixes #612

chore(docs): Update Readme and limitations docs

---

pkg/renderer/sgml/html5/table.go
pkg/renderer/sgml/html5/table_test.go
pkg/renderer/sgml/html5/templates.go
pkg/renderer/sgml/image.go
pkg/renderer/sgml/sgml_renderer.go
pkg/renderer/sgml/table.go
pkg/renderer/sgml/templates.go
pkg/renderer/sgml/xhtml5/table.go
pkg/renderer/sgml/xhtml5/table_test.go
pkg/types/attributes.go

First baby step in table styling, this uses the same approach
used for image captions, only for tables.

feature(renderer): Support customizable table captions

---

libasciidoc_test.go
pkg/renderer/sgml/html5/document_details_test.go
pkg/renderer/sgml/html5/html5.go
pkg/renderer/sgml/html5/html5_test.go
pkg/renderer/sgml/xhtml5/document_details_test.go
pkg/renderer/sgml/xhtml5/xhtml5.go
pkg/renderer/sgml/xhtml5/xhtml5_test.go

feature(renderer): Closing html tag should have a newline appended

---

README.adoc

chore(project): include Asciidoc trademark in README

---

pkg/parser/quoted_text_test.go
pkg/renderer/sgml/html5/quoted_text_test.go

issue was fixed by #755, verifying it here
Fixes #748

test(parser/renderer): verify quoted text role with specoal chars

---

CHANGELOG.md

chore(project): update CHANGELOG.md for v0.5.0

---

pkg/parser/delimited_block_test.go
pkg/parser/document_processing_apply_substitutions.go
pkg/renderer/sgml/html5/delimited_block_test.go
pkg/renderer/sgml/xhtml5/delimited_block_test.go

fix(parser): ignore special chars in passthrough blocks

---

CHANGELOG.md

chore(project): update CHANGELOG.md for v0.5.1

---

pkg/parser/delimited_block_example_test.go
pkg/parser/delimited_block_listing_test.go
pkg/parser/document_processing_apply_custom_substitutions_test.go
pkg/parser/document_processing_apply_substitutions.go
pkg/parser/parser.go
pkg/parser/parser.peg
pkg/renderer/sgml/delimited_block_listing.go
pkg/renderer/sgml/html5/delimited_block_listing_test.go
pkg/renderer/sgml/paragraph.go
pkg/types/attributes.go
pkg/types/types.go

including support for custom substitutions
Fixes #778

feat(parser/renderer): support 'listing' paragraphs

---

pkg/parser/delimited_block_source_test.go
pkg/parser/parser.go
pkg/parser/parser.peg
pkg/renderer/sgml/delimited_block_source.go
pkg/renderer/sgml/html5/delimited_block_source_test.go
pkg/renderer/sgml/html5/delimited_block_source_tmpl.go
pkg/types/attributes.go
pkg/types/types.go

feat(parser/renderer): support 'nowrap' option on source blocks

---

pkg/parser/attributes_test.go
pkg/parser/document_attributes_test.go
pkg/parser/document_processing_apply_substitutions.go
pkg/parser/document_processing_apply_substitutions_test.go
pkg/parser/document_processing_include_toc_placeholder.go
pkg/parser/document_processing_include_toc_placeholder_test.go
pkg/parser/document_processing_test.go
pkg/parser/parser.go
pkg/parser/parser.peg
pkg/parser/section_test.go
pkg/types/attributes.go
pkg/types/types.go
pkg/types/types_utils.go

feat(parser): support attribute substitution in attribute declaration

---

CHANGELOG.md

chore(project): update CHANGELOG.md for v0.6.0

---

.github/workflows/ci-build.yml

chore(build): build, test and lint with Go 1.16 and 1.17

---

pkg/parser/document_preprocessing_include_files_test.go
pkg/renderer/sgml/html5/file_inclusion_test.go
test/includes/table_common.txt
test/includes/table_parent.adoc
test/includes/table_specific.txt

test(parser/renderer): verify file inclusions in tables

---

pkg/types/attributes.go
pkg/types/types.go

chore(types): remove unused code

---

pkg/parser/delimited_block_listing_test.go
pkg/parser/delimited_block_literal_test.go
pkg/parser/delimited_block_verse_test.go

test: verbatim substitution on listing block

---

libasciidoc_test.go
pkg/parser/document_processing_aggregate.go
pkg/parser/document_processing_aggregate_test.go
pkg/parser/section_test.go
pkg/renderer/context.go
pkg/renderer/renderer_suite_test.go
pkg/renderer/section_numbering.go
pkg/renderer/section_numbering_test.go
pkg/renderer/sgml/html5/section.go
pkg/renderer/sgml/html5/section_test.go
pkg/renderer/sgml/html5/table_of_contents.go
pkg/renderer/sgml/html5/table_of_contents_test.go
pkg/renderer/sgml/renderer.go
pkg/renderer/sgml/section.go
pkg/renderer/sgml/sgml_renderer.go
pkg/renderer/sgml/table_of_contents.go
pkg/types/attributes.go
pkg/types/types.go
pkg/validator/validator.go

feat(renderer): section numbering

---

pkg/parser/quoted_string_test.go
pkg/renderer/sgml/html5/quoted_string_test.go
pkg/renderer/sgml/html5/string_test.go
pkg/renderer/sgml/xhtml5/quoted_string_test.go
pkg/types/non_alphanumeric_replacement_test.go
pkg/types/non_alphanumerics_replacement.go
pkg/types/types.go

support quoted strings and ignore unnecessary characters
fixes #920

fix(types): section id generation

---

pkg/renderer/sgml/paragraph.go
pkg/types/attributes.go
pkg/types/types.go

Part of the TODOs to address ;)

chore(types): remove unused/duplicate code

---

LIMITATIONS.adoc

remove outdated content
fixes #936

chore(doc): update LIMITATIONS.adoc

---

pkg/parser/document_processing.go
pkg/parser/document_processing_parse_fragments.go

refactor(parser): change 'info' to 'debug' level for log messages

---

pkg/renderer/sgml/renderer.go

chore(renderer): remove unused funcs

---

pkg/parser/footnote_test.go
pkg/parser/ordered_list_test.go
pkg/renderer/sgml/xhtml5/index_terms_test.go
test/test_suite_test.go

chore(build): remove left-over 'nolint:golint' comments

---

.github/workflows/ci-bench.yml
.github/workflows/ci-release.yml
make/bench.mk
make/git.mk
make/profile.mk

chore(bench): display bench stats as comment in PR

---

.github/workflows/ci-build.yml

chore(project): build and test with Go 1.18

---

pkg/parser/parser.peg
pkg/types/types.go

refactor(parser): simplify 'InlineFootnote' rule

---

pkg/renderer/sgml/delimited_block_admonition.go
pkg/renderer/sgml/delimited_block_example.go
pkg/renderer/sgml/delimited_block_fenced.go
pkg/renderer/sgml/delimited_block_listing.go
pkg/renderer/sgml/delimited_block_markdown_quote.go
pkg/renderer/sgml/delimited_block_quote.go
pkg/renderer/sgml/delimited_block_sidebar.go
pkg/renderer/sgml/delimited_block_source.go
pkg/renderer/sgml/delimited_block_verse.go
pkg/renderer/sgml/html5/delimited_block_listing_test.go
pkg/renderer/sgml/image.go
pkg/renderer/sgml/list.go
pkg/renderer/sgml/literal_blocks.go
pkg/renderer/sgml/paragraph.go
pkg/renderer/sgml/table.go

support elements such as links, etc.
follow-up of #999
Fixes #956

feat(renderer): support elements in titles

---

pkg/parser/document_processing_aggregate.go
pkg/renderer/sgml/html5/image_test.go
pkg/renderer/sgml/paragraph.go

chore(renderer): remove unused params in paragraph template

---

pkg/parser/image_test.go
pkg/renderer/sgml/html5/cross_reference_test.go
pkg/types/types.go

feat(parser): support cross references to images with ID and title

---

pkg/parser/cross_reference_test.go
pkg/parser/document_processing_aggregate.go
pkg/renderer/sgml/html5/cross_reference_test.go
pkg/types/types.go

feat(parser): support natural cross references within lists

---

make/bench.mk

compare old vs new, not the opposite :/

chore(build): fix benchstat reports

---

libasciidoc.go
pkg/configuration/configuration.go
pkg/renderer/sgml/cross_reference.go
pkg/renderer/sgml/delimited_block_source.go
pkg/renderer/sgml/delimited_block_verse.go
pkg/renderer/sgml/elements.go
pkg/renderer/sgml/footnote_reference.go
pkg/renderer/sgml/html5/footnote_reference.go
pkg/renderer/sgml/html5/footnote_reference_test.go
pkg/renderer/sgml/html5/manpage.go
pkg/renderer/sgml/html5/table_of_contents.go
pkg/renderer/sgml/html5/templates.go
pkg/renderer/sgml/html5/user_macro_test.go
pkg/renderer/sgml/html_escape.go
pkg/renderer/sgml/inline_elements.go
pkg/renderer/sgml/paragraph.go
pkg/renderer/sgml/sgml.go
pkg/renderer/sgml/sgml_renderer.go
pkg/renderer/sgml/sgml_renderer_plain_text.go
pkg/renderer/sgml/special_character.go
pkg/renderer/sgml/table_of_contents.go
pkg/renderer/sgml/templates.go
pkg/renderer/sgml/xhtml5/user_macro_test.go
pkg/types/types.go
testsupport/html5_matcher.go
testsupport/preparse_document.go
testsupport/render_html5.go

move plaintext rendering to separate funcs

refactor(renderer): init and plaintext rendering

---

libasciidoc.go
pkg/renderer/sgml/special_character.go

refactor(renderer): simplify rendering of special characters

---

libasciidoc_test.go
pkg/parser/document_processing_aggregate.go
pkg/parser/document_processing_insert_preamble_test.go

fix(parser): no need for a preamble wrapper if no title

---

pkg/parser/attribute_substitution_test.go
pkg/parser/attributes_test.go
pkg/parser/cross_reference_test.go
pkg/parser/delimited_block_example_test.go
pkg/parser/delimited_block_listing_test.go
pkg/parser/delimited_block_literal_test.go
pkg/parser/delimited_block_verse_test.go
pkg/parser/document_header_test.go
pkg/parser/document_preprocessing_include_files_test.go
pkg/parser/document_processing_aggregate.go
pkg/parser/document_processing_parse_fragments.go
pkg/parser/document_test.go
pkg/parser/escape_backslash_test.go
pkg/parser/image_test.go
pkg/parser/inline_button_test.go
pkg/parser/inline_menu_test.go
pkg/parser/line_break_test.go
pkg/parser/link_test.go
pkg/parser/paragraph_test.go
pkg/parser/parser.peg
pkg/parser/passthrough_test.go
pkg/parser/section_test.go
pkg/parser/table_test.go
pkg/renderer/sgml/sgml.go
pkg/renderer/sgml/table_of_contents.go
pkg/types/types.go

refactor(parser): simplify DocumentHeader grammar rule and type

---

go.mod
go.sum
pkg/renderer/sgml/delimited_block_source.go
pkg/renderer/sgml/html5/delimited_block_source_test.go
pkg/renderer/sgml/html5/paragraph_test.go
pkg/renderer/sgml/xhtml5/delimited_block_source_test.go
pkg/renderer/sgml/xhtml5/paragraph_test.go

include changes in expected rendering
Fixes #1058

chore(renderer): update alecthomas/chroma to v2.3.0

---

pkg/parser/table_test.go
pkg/renderer/sgml/html5/table_test.go
pkg/renderer/sgml/table.go
pkg/types/types.go

feat(renderer): table columns as headers

---

.goreleaser.yml

support 'parser/renderer' scope and 'refactoring' group of commits

chore(project): update GoReleaser config

---

pkg/renderer/sgml/html_escape.go
pkg/renderer/sgml/sgml.go

Also sort FuncMap functions.
Fixes #854

Add unescape function to template FuncMap
