bytesparadise/libasciidoc

renderer/html5/html5_renderer.go, renderer/html5/html5_renderer_test.go
using the `html/template` package to produce the
HTML output from a given array of `types.DocElement`.
=> feat(rendering): first draft of HTML5 rendering

parser/asciidoc-grammar.peg, parser/asciidoc_parser_test.go, types/types.go
reorganize the `BlockImage` type as a super-type that contains
a single `BlockImageMacro` element preceeded with multiple, optional
'meta' elements (ID, link, title).
=> feat(parser) improve block image parsing

parser/asciidoc-grammar.peg, parser/asciidoc_parser_test.go, parser/quotedtext_test.go, renderer/html5/html5_renderer.go, types/type_utils.go, types/types.go
Bold quote can contain italic and monospaced quotes, and vice-versa.
Also refactor `types/typ_utils.go` by removing duplicate/similar functions.
Also remove unnecessary golang blocks in grammar (when no specific
initialization is done)
=> feat(parser): support italic and monospace quotes, as well as nested quotes

parser/asciidoc-grammar.peg, parser/asciidoc_parser_test.go, parser/delimited_block_test.go, renderer/html5/delimited_block.go, renderer/html5/delimited_block_test.go, renderer/html5/image.go, renderer/html5/image_test.go, renderer/html5/paragraph.go, renderer/html5/renderer.go, renderer/html5/renderer_test.go, types/type_utils.go, types/types.go
Support fences (```)
Also, more strict comparisons in test (not ignoring '\n')
=> feat(parser/renderer): support for delimited source blocks

glide.lock, glide.yaml, parser/asciidoc-grammar.peg, parser/asciidoc_parser_test.go, renderer/html5/heading.go, renderer/html5/heading_test.go, renderer/html5/inline_content.go, renderer/html5/paragraph.go, renderer/html5/renderer.go, types/type_utils.go, types/type_utils_test.go, types/types.go
Default heading ID based on the content of the ID, with some transformation
to make it a valid CSS selector.
Add support for Visitor on all `types.DocElement` implementations.
=> feat(renderer): render headings with support for default and custom ID

.gitignore, .travis.yml, Makefile, glide.lock, glide.yaml, parser/asciidoc_parser_test.go, parser/block_image_test.go, parser/delimited_block_test.go, parser/parser_suite_test.go, parser/quotedtext_test.go, renderer/html5/delimited_block_test.go, renderer/html5/heading_test.go, renderer/html5/html5_suite_test.go, renderer/html5/image_test.go, renderer/html5/quoted_text_test.go, renderer/html5/renderer_test.go, test/log_init.go, types/type_utils_test.go, types/types.go, types/types_suite_test.go
Existing code was migrated using ginkgo CLI, then
adapted.
Also move the "debug" flag detection into a "test"
pkg that needs to be imported in other tests
=> chore(project): use ginkgo to run the tests

glide.lock, glide.yaml, renderer/html5/paragraph.go, renderer/html5/renderer_test.go, renderer/html5/section.go, renderer/html5/section_test.go, renderer/html5/string.go, types/types.go
all blocks before first section of level 2 are wrapped
in a 'preamble' div.
also, update ginkgo and gomega dependencies
=> feat(renderer): render section preamble

libasciidoc.go, libasciidoc_test.go, parser/asciidoc_parser_test.go, parser/blank_line_test.go, parser/delimited_block_test.go, parser/external_link_test.go, parser/image_test.go, parser/list_test.go, parser/meta_elements_test.go, parser/paragraph_test.go, parser/quoted_text_test.go, parser/section_test.go, renderer/html5/delimited_block.go, renderer/html5/image.go, renderer/html5/list_item.go, renderer/html5/paragraph.go, renderer/html5/quoted_text.go, renderer/html5/renderer.go, renderer/html5/renderer_test.go, renderer/html5/section.go, renderer/html5/string.go, renderer/html5/template_utils.go, renderer/options.go, types/document_metadata.go, types/grammar_types.go, types/type_utils.go, types/type_utils_test.go
Include header and footer in the full document
When rendering the body only, the function returns the document
metadata, including the document title
=> feat(renderer): render full document

libasciidoc.go, parser/asciidoc-grammar.peg, parser/asciidoc_parser_test.go, parser/blank_line_test.go, parser/delimited_block_test.go, parser/document_attributes_test.go, parser/external_link_test.go, parser/image_test.go, parser/list_test.go, parser/meta_elements_test.go, parser/paragraph_test.go, parser/quoted_text_test.go, parser/section_test.go, renderer/html5/blank_line_test.go, renderer/html5/document_attribute_test.go, renderer/html5/paragraph_test.go, renderer/html5/renderer.go, types/document_metadata.go, types/grammar_types.go, types/type_utils.go
Support document attribute in the form: ":name: value" or
":name:" at any location in the document.
For now, document attributes are silently ignored during
rendering.
Rename "Metadata" -> "Attributes" for document and elements.
=> feat(parser/renderer): support for document attributes

context/context.go, libasciidoc.go, libasciidoc_test.go, parser/asciidoc-grammar.peg, parser/document_attributes_test.go, renderer/html5/delimited_block.go, renderer/html5/document_attribute.go, renderer/html5/document_attribute_test.go, renderer/html5/image.go, renderer/html5/inline_content.go, renderer/html5/list_item.go, renderer/html5/paragraph.go, renderer/html5/quoted_text.go, renderer/html5/renderer.go, renderer/html5/renderer_test.go, renderer/html5/section.go, renderer/html5/string.go, types/document_metadata.go, types/grammar_types.go, types/type_utils.go
Also: introduce a custom `Context` type that includes the document
being processed, giving access to document attributes when declaration,
reset and subsitutions elements are processed/rendered.
Also, rename type `DocumentAttribute` -> `DocumentAttributeDeclaration` while
introducing `DocumentAttributeSubstitution` and `DocumentAttributeReset` types.
=> feat(parser/renderer): support for document attributes reset and substitutions

.gitignore, parser/asciidoc_parser.go
this will avoid each third-party project that wants
to use this library to have to deal with the code
generation by itself.
=> chore(project): include generated parser file

glide.lock, glide.yaml, parser/asciidoc-grammar.peg, parser/asciidoc_parser.go, parser/frontmatter_test.go, renderer/html5/document_attribute.go, renderer/html5/document_attribute_test.go, types/document_attributes.go, types/grammar_types.go
Front-matter tokens must be `---`.
Front-matter content is parsed using the `gopkg.in/yaml.v2`
library: no need to recreate the YAML grammar here !
=> feat(parser): support front-matter in YAML format

glide.lock, parser/asciidoc-grammar.peg, parser/asciidoc_parser.go, parser/asciidoc_parser_test.go, parser/delimited_block_test.go, parser/document_attributes_test.go, parser/literal_block_test.go, parser/section_test.go, renderer/html5/blank_line_test.go, renderer/html5/delimited_block.go, renderer/html5/delimited_block_test.go, renderer/html5/literal_blocks.go, renderer/html5/renderer.go, types/grammar_types.go, types/type_utils.go
support for literal blocks in the form of:
=> feat(parser/renderer): support for literal blocks

codecov.yml
main goal is to ignore the `parser/asciidoc_parser.go`
file which is generated and which contains some features
that are not used (yet).
=> chore(project): configure codecov

CONTRIBUTE.adoc, CONTRIBUTE.html, LIMITATIONS.adoc, LIMITATIONS.html, README.adoc, README.html, parser/asciidoc-grammar.peg, parser/asciidoc_parser.go, parser/quoted_text_test.go, renderer/html5/quoted_text_test.go, types/grammar_types.go, types/type_utils.go
=> feat(parser): support double punctuation in quoted text

README.adoc, parser/asciidoc-grammar.peg, parser/asciidoc_parser.go, parser/delimited_block_test.go, renderer/html5/delimited_block.go, renderer/html5/delimited_block_test.go, types/grammar_types.go
=> feat(parser/renderer): support listing blocks

.travis.yml
=> chore(build): allow fast-finish on Travsi-ci

parser/asciidoc-grammar.peg, parser/asciidoc_parser.go, parser/asciidoc_parser_test.go, parser/document_attributes_test.go, parser/table_of_contents_test.go, renderer/html5/delimited_block.go, renderer/html5/document.go, renderer/html5/document_attribute.go, renderer/html5/image.go, renderer/html5/inline_content.go, renderer/html5/list_item.go, renderer/html5/literal_blocks.go, renderer/html5/paragraph.go, renderer/html5/passthrough.go, renderer/html5/quoted_text.go, renderer/html5/renderer.go, renderer/html5/section.go, renderer/html5/string.go, renderer/html5/table_of_contents.go, renderer/html5/table_of_contents_test.go, types/document_attributes.go, types/grammar_types.go
also, refactor `renderXYZ()` functions to use references rather
than full copy of elements to render.
=> feat(parser/renderer): support TOC placement in preamble

renderer/html5/external_link.go, renderer/html5/external_link_test.go, renderer/html5/renderer.go
=> feat(renderer): render external links

parser/admonition_test.go, parser/asciidoc-grammar.peg, parser/asciidoc_parser.go, parser/labeled_list_test.go, parser/literal_block_test.go, parser/paragraph_test.go, parser/unordered_list_test.go, renderer/html5/adminition_test.go, renderer/html5/admonition.go, renderer/html5/blank_line_test.go, renderer/html5/literal_blocks.go, renderer/html5/renderer.go, types/grammar_types.go
support admonition paragraphs and blocks (ie,
"masquerade" on paragraph)
Fixes #67 
=> feat(parser/renderer): support admonitions

renderer/html5/document.go, renderer/html5/document_details_test.go, renderer/html5/document_test.go, renderer/html5/paragraph.go, renderer/html5/renderer.go
move call to rendering paragraph elements in the
template instead of a function.
Fixes #74
=> refactor(renderer): Refactor paragraph renderer

types/grammar_types.go
More megacheck findings:
types/grammar_types.go:279:12: the argument is already a string, there's no need to use fmt.Sprintf (S1025)
types/grammar_types.go:280:2: unnecessary nil check around range (S1031)
=> types: tidy up initials func

cmd/libasciidoc/root_cmd.go, cmd/libasciidoc/root_cmd_test.go
adds flag `--log` as follows
```
--log string      log level to set {debug, info, warning, error, fatal, panic} (default "warning")
```
=> feat(cmd): add support to specify log level

README.adoc, parser/admonition_test.go, parser/asciidoc-grammar.peg, parser/asciidoc_parser.go, parser/blank_line_test.go, parser/delimited_block_test.go, parser/document_attributes_test.go, parser/element_attributes_test.go, parser/frontmatter_test.go, parser/image_test.go, parser/labeled_list_test.go, parser/literal_block_test.go, parser/paragraph_test.go, parser/passthrough_test.go, parser/quoted_text_test.go, parser/section_test.go, parser/table_of_contents_test.go, parser/unordered_list_test.go, renderer/html5/admonition.go, renderer/html5/document.go, renderer/html5/image.go, renderer/html5/paragraph.go, renderer/html5/section.go, renderer/html5/table_of_contents.go, types/document_xrefs.go, types/grammar_types.go
Use a `map[string]interface{}` for all attributes,
incuding `ID` and `Title`.
Fixes #87
=> refactor(parser): refactor attributes (#87)

cmd/libasciidoc/root_cmd.go, cmd/libasciidoc/root_cmd_test.go
see #83 is this what this issue refers to?
=> feat(cmd): add flag to suppress header/footer

cmd/libasciidoc/root_cmd.go, cmd/libasciidoc/root_cmd_test.go, cmd/libasciidoc/test/admonition.adoc
See #96 
```
libasciidoc is a tool to generate an html output from an asciidoc file
Positional args:
If no files are specified, input is read from STDIN
If more than 1 file is specified, then output is written to ".html" file alongside the source file
Usage:
libasciidoc FILE... [flags]
libasciidoc [command]
Available Commands:
help        Help about the command
version     Print the version number of libasciidoc
Flags:
-h, --help               help for libasciidoc
--log string         log level to set {debug, info, warning, error, fatal, panic} (default "warning")
-s, --no-header-footer   Do not render header/footer (Default: false)
Use "libasciidoc [command] --help" for more information about a command.
```
=> refactor(cmd): make cmd args in line with asciidoctor

Makefile
Also, a bit of cleaning in the Makefile.
Fixes #94
=> feat(make): add goal to build executable (#94)

Makefile, libasciidoc.go, pkg/parser/asciidoc-grammar.peg, pkg/parser/asciidoc_parser.go, pkg/parser/asciidoc_parser_test.go, pkg/renderer/html5/renderer_test.go, pkg/types/grammar_types_utils.go
also, small refactoring in the grammar with regards to spaces
after attributes
Fixes #117
=> feat(parser): use the `memoize` option in the parser to improve perfs

pkg/renderer/html5/article.adoc, pkg/renderer/html5/article_adoc_test.go
main issue was fixed in 9f1e39437a2a6b61c19eb3f4dde12fc4ad4cae25
but this commit add a test to ensure that the `article.adoc` file
will remain parseable.
fixes #153
=> fix(parser): fix parsing issue when processing 'article.adoc'

cmd/libasciidoc/root_cmd.go, libasciidoc.go, pkg/renderer/context.go, pkg/renderer/html5/image.go, pkg/renderer/html5/image_test.go
`imagesdir` attribute is used if the image path is
relative. If it's a valid URL or an absolute path
on the FS, it's not used.
Fixes #160
=> feat(renderer): support 'imagesdir' attribute

pkg/parser/image_test.go, pkg/renderer/html5/image_test.go, pkg/types/grammar_types.go
wrong usage of `string.TrimRight` instead
of `strings.TrimSuffix`. Fix applied for
image blocks and inline images as well.
fixes #198
=> fix(parser): incorrect default image alt

pkg/parser/section_test.go, pkg/renderer/html5/section_test.go, pkg/types/document_xrefs.go
change section id when collecting references, if
another section (or element) with the same id already
exists and was referenced.
fixes #184
=> fix(parser/renderer): unique section id

.gitignore, Makefile, fixtures_test.go, test/fixtures/basic.adoc, test/fixtures/basic.html, test/fixtures/encoding.adoc, test/fixtures/encoding.html, test/fixtures/exline-mono.adoc, test/fixtures/exline-mono.html, test/fixtures/includes/chapter-a.adoc, test/fixtures/includes/child-include.adoc, test/fixtures/includes/grandchild-include.adoc, test/fixtures/lists.adoc, test/fixtures/lists.html, test/fixtures/master.adoc, test/fixtures/master.html, test/fixtures/parent-include.adoc, test/fixtures/parent-include.html, test/fixtures/sample.adoc, test/fixtures/sample.html, test/fixtures/sscript.adoc, test/fixtures/sscript.html
Create a basic framework for adding test fixtures. The workflow is to
add .adoc files to the fixtures folder with corresponding .html files to
act as the "golden" HTML output. Include files are in the includes
sub-folder so as to differentiate them from the main fixture files.
Failed tests show a diff against the golden output.
Tests are currently hidden behind a "fixtures" build tag. Use
"-tags=fixtures" when running tests to activate.
The existing test fixtures are mostly taken from the asciidoctor test
fixtures. The golden files were generated with asciidoctor v1.5.7.1
using the "-s" option.
Updates #79
=> test(fixtures): add fixtures testing framework

.travis.yml, Makefile
=> feat(build): add windows and osx builds to Travis

Makefile, cmd/libasciidoc/root_cmd.go, cmd/libasciidoc/root_cmd_test.go, cmd/libasciidoc/version_cmd.go
also, make sure output is written in the command output,
not always the console (which avoids unnecessary logs
in the console during tests)
also, avoid duplicate error messages when file to process
is not found
also, add a goal to run tests without coverage
fixes #236
=> fix(cli): command hangs when no arg is provided

pkg/parser/delimited_block_test.go, pkg/parser/document_attributes_test.go, pkg/parser/footnote_test.go, pkg/parser/inline_elements_test.go, pkg/parser/list_test.go, pkg/parser/paragraph_test.go, pkg/parser/passthrough_test.go, pkg/parser/quoted_text_test.go, pkg/parser/section_test.go, pkg/parser/table_test.go, pkg/renderer/html5/quoted_text.go, pkg/types/grammar_types.go, pkg/types/grammar_types_utils_test.go
=> refactor(types): use Kind field for quoted text kind

pkg/parser/list_test.go, pkg/renderer/html5/labeled_list.go, pkg/renderer/html5/labeled_list_test.go
=> feat(renderer): support title on labeled lists

pkg/parser/delimited_block_test.go, pkg/parser/list_test.go, pkg/renderer/html5/delimited_block.go, pkg/renderer/html5/delimited_block_test.go, pkg/renderer/html5/document.go, pkg/renderer/html5/document_details.go, pkg/renderer/html5/image.go, pkg/renderer/html5/labeled_list.go, pkg/renderer/html5/labeled_list_test.go, pkg/renderer/html5/literal_blocks.go, pkg/renderer/html5/ordered_list.go, pkg/renderer/html5/paragraph.go, pkg/renderer/html5/quoted_text.go, pkg/renderer/html5/section.go, pkg/renderer/html5/string.go, pkg/renderer/html5/table.go, pkg/renderer/html5/table_of_contents.go, pkg/renderer/html5/unordered_list.go, pkg/types/element_attributes.go
also, use the `html.EscapeString` on all titles
fixes #271
=> feat(renderer): support "Q and A" labeled lists

pkg/renderer/html5/labeled_list.go, pkg/renderer/html5/labeled_list_test.go, pkg/renderer/html5/ordered_list.go, pkg/renderer/html5/ordered_list_test.go, pkg/renderer/html5/renderer.go, pkg/renderer/html5/unordered_list.go, pkg/renderer/html5/unordered_list_test.go
Apply on all lists (ordered, unordered, labelled)
fixes #270
=> fix(renderer): wrap continuing element in <div>

pkg/parser/asciidoc-grammar.peg, pkg/parser/comment_test.go
=> fix(parser): support spaces and tabs ahead of single line comment

pkg/parser/labeled_list_test.go, pkg/parser/ordered_list_test.go, pkg/parser/unordered_list_test.go, pkg/types/grammar_types.go
attach child elements of all sub levels when a new item of a given
level is processed
also verified on unordered list and labeled list.
fixes #293
=> fix(types): attach child elements to correct parent in ordered list

pkg/parser/asciidoc-grammar.peg, pkg/parser/passthrough_test.go, pkg/renderer/html5/document_attribute_substitution.go, pkg/renderer/html5/document_attribute_substitution_test.go, pkg/renderer/html5/inline_elements.go, pkg/renderer/html5/passthrough_test.go, pkg/renderer/html5/renderer.go
unescape the document attributes substitution before it
is escaped again
fixes #295
=> fix(renderer): avoid double encoding of document attributes

.gitignore, pkg/renderer/html5/section.go, pkg/renderer/html5/section_test.go, pkg/types/document_attributes.go
depends if the document has a section level 0 (ie, a title)
fixes #298
=> fix(renderer): do not always render preamble withing wrapper

Makefile, pkg/parser/asciidoc-grammar.peg, pkg/parser/file_inclusion_test.go, pkg/renderer/file_inclusions.go, pkg/renderer/file_inclusions_test.go, pkg/renderer/html5/delimited_block.go, pkg/renderer/html5/delimited_block_test.go, pkg/renderer/html5/file_inclusion_test.go, pkg/renderer/html5/renderer.go, pkg/types/grammar_types.go
parsing the .adoc file with a new entry point to ignore
the section (just get paragraphs, etc.)
fixes #310
=> feat(parser/renderer): support adoc file inclusion in delimited blocks

.travis.yml, appveyor.yml
retain/build only 3 stable versions of Go
Fixes #323
=> chore(build): build with go 1.12 on Travis-ci and AppVeyor

pkg/parser/asciidoc-grammar.peg, pkg/parser/file_inclusion_test.go, pkg/renderer/file_inclusion.go, pkg/renderer/file_inclusion_test.go, pkg/renderer/html5/file_inclusion_test.go, pkg/renderer/pre_render.go, pkg/renderer/preamble.go, pkg/renderer/preamble_test.go, pkg/renderer/table_of_contents.go, pkg/renderer/table_of_contents_test.go, pkg/types/element_attributes.go, pkg/types/grammar_types.go, pkg/types/grammar_types_test.go
support multiple line ranges separated by semi colons or by
commas if declared within quotes.
Fixes #315
=> feat(parser/renderer): support file inclusion with line ranges

Makefile, pkg/parser/asciidoc-grammar.peg, pkg/renderer/file_inclusion.go, pkg/renderer/file_inclusion_test.go, pkg/renderer/html5/file_inclusion_test.go, pkg/renderer/html5/includes/parent-include.adoc
support recursive file inclusions
also: simply code for renderer, avoid duplicate/similar funcs
fixes #311
=> feat(parser/renderer): support recursive file inclusions

pkg/parser/asciidoc-grammar.peg, pkg/parser/paragraph_test.go, pkg/parser/passthrough_test.go, pkg/renderer/html5/passthrough_test.go, pkg/types/grammar_types.go, pkg/types/grammar_types_utils.go
Do not accept content such as `+ foo bar+` or `+foo bar +`
as valid passthrough: no space allowed after opening `+`
or before closing `+` characters.
Fixes #337
=> fix(parser): do not allow spaces in singleplus passthough

pkg/renderer/html5/delimited_block.go, pkg/renderer/html5/delimited_block_test.go, pkg/renderer/html5/file_inclusion_test.go, pkg/renderer/html5/ordered_list_test.go
in particular, all `<`, `>`, `'` and `"` characters
Fixes #341
=> fix(renderer): escape content of listing and source blocks

Makefile, cmd/libasciidoc/cmd_suite_test.go, cmd/libasciidoc/main.go, cmd/libasciidoc/root_cmd.go, libasciidoc.go, libasciidoc_suite_test.go, libasciidoc_test.go, pkg/log/log_init.go, pkg/parser/asciidoc-grammar.peg, pkg/parser/document_preprocessing.go, pkg/parser/file_inclusion_test.go, pkg/parser/parser_suite_test.go, pkg/renderer/html5/file_inclusion_test.go, pkg/renderer/html5/html5_suite_test.go, pkg/renderer/renderer_suite_test.go, pkg/types/grammar_types.go, pkg/types/types_suite_test.go, test/test_suite_test.go, testsupport/log_init.go
Retrieve the whole file inclusion text during parsing so it can be
included in an error message.
Also, refactor the log format and configuration, splitting the
setup in a separate package for the tests, to avoid the conflict
of flags parsing with spf13/cobra when running from CL.
Fixes #319
=> refactor(parser): do not report error when file to include is missing

pkg/parser/asciidoc-grammar.peg, pkg/parser/document_preprocessing.go, pkg/parser/file_inclusion_test.go, pkg/renderer/html5/file_inclusion_test.go, pkg/types/grammar_types.go, pkg/types/grammar_types_test.go
attribute in path is resolved during preprocessing.
Fixes #317
=> feat(parser): support attribute in path of file to include

README.adoc, pkg/parser/asciidoc-grammar.peg, pkg/parser/user_macro_test.go, pkg/renderer/context.go, pkg/renderer/html5/renderer.go, pkg/renderer/html5/user_macro.go, pkg/renderer/html5/user_macro_test.go, pkg/renderer/options.go, pkg/types/grammar_types.go
fixes #334 
* add parse rules for user macro to parser.
* add `renderer.DefineMacro()` that returns `renderer.Option` to renderer.
* user can define a rendering function for macro by call `renderer.DefineMacro()` and pass to `renderer.Wrap()`.
ex.
```go
func helloMacro(cm types.UserMacro) ([]byte, error) {
// render content
}
...
renderer.Wrap(context.Background(), doc, renderer.DefineMacro("hello", helloMacro))
...
```
=> feat(parser/renderer): add user macro feature

Makefile, pkg/parser/asciidoc-grammar.peg, pkg/parser/bench_test.go, pkg/parser/document_preprocessing.go, pkg/parser/external_link_test.go, pkg/parser/footnote_test.go, pkg/parser/image_test.go, pkg/parser/inline_elements_test.go, pkg/parser/quoted_text_test.go, pkg/renderer/html5/attribution.go, pkg/renderer/html5/document_attribute_substitution_test.go, pkg/renderer/html5/external_link.go, pkg/renderer/html5/external_link_test.go, pkg/renderer/html5/footnote_test.go, pkg/renderer/html5/quoted_text_test.go, pkg/renderer/html5/renderer.go, pkg/types/element_attributes.go, pkg/types/grammar_types.go, pkg/types/grammar_types_test.go, pkg/types/grammar_types_utils.go
Also, significant refactoring on the parsing of quoted text
Also, when a link has no `text` attribute, then omit in the
output AST.
Fixes #356
=> fix(parser/renderer): support quoted text in links

Makefile, pkg/parser/bench_test.go
also, refactor the benchmarks to use subbenchs.
fixes #374
=> refactor(build/parser): add goal to run parser benchs

pkg/parser/asciidoc-grammar.peg, pkg/parser/asciidoc_parser.go, pkg/parser/delimited_block_test.go, pkg/parser/file_inclusion_test.go, pkg/parser/footnote_test.go, pkg/parser/link_test.go, pkg/parser/paragraph_test.go, pkg/types/element_attributes.go, pkg/types/grammar_types.go
reduces some rules and avoids intermediate
memory allocations (converting a []byte to
string)
fixes #376
=> refactor(parser): simplify grammar

pkg/parser/asciidoc-grammar.peg, pkg/parser/asciidoc_parser.go, pkg/parser/bench_test.go, pkg/types/element_attributes.go
in particular on section title and
on some element attribute rules,
also, introduce `EOLS` as `WS* EOL` for readability
updates #376 
=> refactor(parser): optimize/reduce grammar

pkg/parser/link_test.go, pkg/parser/parser.go, pkg/parser/parser.peg
supoort text with comma and without being surrounded
by double quotes if no other attribute is defined,
or require the (positional) text attribute to be
surrounded with double quotes if it contains commas
and there are other attributes in the link macro.
fixes #388
=> fix(parser): support commas in link text attribute

pkg/renderer/html5/file_inclusion_test.go, pkg/renderer/html5/html5_test.go
same assertions as in `pkg/parser`, but in `pkg/renderer/html5`
this time.
fixes #394
=> test(renderer): verify log output when error is logged

go.sum, pkg/parser/file_inclusion_test.go, pkg/renderer/html5/file_inclusion_test.go, pkg/types/types_test.go, testsupport/console.go, testsupport/console_test.go, testsupport/testsupport_suite_test.go
allows support for 'debug' output in console
fixes #410
=> refactor(test): support multiple lines in console assertions

.codecov.yml
Require a coverage of 80% and allow for up to 2% of drop in PRs
Fixes #414
=> chore(project): configure codecov with range and threshold

pkg/parser/file_inclusion_test.go, pkg/parser/link_test.go, pkg/parser/parser.go, pkg/parser/parser.peg
added a lot of missing characters, but excluded
the `[` and `]` as they are used to pass arguments
in external and relative links.
Fixes #416:
=> fix(parser): support valid characters in URLs

pkg/parser/file_inclusion_test.go, testsupport/console_matcher.go, testsupport/console_matcher_test.go
added a Gomega matcher to verify that no message with any of the given
levels was logged
added checks to some use-cases
fixes #408
=> test(parser): verify that no message is logged when file inclusion works

pkg/parser/link_test.go, pkg/parser/parser.go, pkg/parser/parser.peg, pkg/parser/user_macro_test.go, pkg/renderer/html5/user_macro_test.go, testsupport/document_block_matcher.go
looks like the `%` character was missing in the previous
fix for link URLs :/
also, prevent spaces in user-defined macro values.
Fixes #419
=> fix(parser): support encoded spaces in link URL

testsupport/comparison.go, testsupport/comparison_test.go, testsupport/console_matcher.go, testsupport/document_block_matcher.go, testsupport/document_block_matcher_test.go, testsupport/document_matcher.go, testsupport/document_matcher_test.go, testsupport/document_metadata_matcher.go, testsupport/document_metadata_matcher_test.go, testsupport/document_preamble_matcher.go, testsupport/document_preamble_matcher_test.go, testsupport/document_toc_matcher.go, testsupport/document_toc_matcher_test.go, testsupport/html5_rendering_matcher.go, testsupport/html5_rendering_matcher_test.go, testsupport/preflight_document_matcher.go, testsupport/preflight_document_matcher_test.go, testsupport/replace_non_alphanumeric_matcher_test.go, testsupport/replace_non_alphanumerics_matcher.go
display a readable diff of the "processed actual" vs "expected"
values
Fixes #421
=> refactor(test): improve failure messages in custom matchers

pkg/parser/file_inclusion.go, pkg/parser/file_inclusion_test.go, pkg/parser/parser.go, pkg/parser/parser.peg, pkg/renderer/html5/file_inclusion_test.go, pkg/types/types.go, pkg/types/types_test.go, test/includes/tag-include-unclosed.adoc, testsupport/comparison.go
Support '*' and '**' wildcards and negated ranges, too.
Fixes #396
=> feat(parser): support wildcards in tag inclusions

libasciidoc.go, libasciidoc_test.go, pkg/parser/file_inclusion.go, pkg/parser/file_inclusion_test.go, pkg/renderer/html5/file_inclusion_test.go, pkg/types/types_suite_test.go, testsupport/comparison.go, testsupport/console_matcher.go, testsupport/html5_rendering_matcher.go, testsupport/log_init.go, testsupport/matcher_options.go, testsupport/preflight_document_matcher.go, testsupport/preflight_document_matcher_test.go, testsupport/testsupport_suite_test.go
use the base dir of the top/root parent as the starting dir
when processing file inclusions
modify matchers to support optional filename
fixes #424
=> fix(parser/renderer): use main file path to start inclusions

pkg/renderer/html5/blank_line_test.go, pkg/renderer/html5/comment_test.go, pkg/renderer/html5/cross_reference_test.go, pkg/renderer/html5/delimited_block_test.go, pkg/renderer/html5/distinct_lists_test.go, pkg/renderer/html5/document.go, pkg/renderer/html5/document_attribute_substitution_test.go, pkg/renderer/html5/document_details_test.go, pkg/renderer/html5/document_test.go, pkg/renderer/html5/file_inclusion_test.go, pkg/renderer/html5/footnote_test.go, pkg/renderer/html5/image_test.go, pkg/renderer/html5/labeled_list_test.go, pkg/renderer/html5/link_test.go, pkg/renderer/html5/literal_block_test.go, pkg/renderer/html5/ordered_list_test.go, pkg/renderer/html5/paragraph_test.go, pkg/renderer/html5/passthrough_test.go, pkg/renderer/html5/quoted_text_test.go, pkg/renderer/html5/section_test.go, pkg/renderer/html5/string_test.go, pkg/renderer/html5/table_of_contents_test.go, pkg/renderer/html5/table_test.go, pkg/renderer/html5/unordered_list_test.go, pkg/renderer/html5/user_macro_test.go, pkg/renderer/options.go, pkg/types/element_attributes.go, testsupport/comparison.go, testsupport/html5_rendering_matcher.go, testsupport/html5_rendering_matcher_test.go
=> refactor(test): remove HTML5ElementMatcher in favor of HTML5BodyMatcher

pkg/parser/file_inclusion_test.go, pkg/renderer/html5/document.go, pkg/renderer/html5/file_inclusion_test.go, pkg/types/types.go, testsupport/console_matcher.go
unless there's a relevant element before. Otherwise,
just retain the section elements
fixes #425
=> fix(renderer): do not include section 0 element

Makefile, pkg/parser/document_preprocessing.go, pkg/parser/file_inclusion.go, pkg/parser/file_inclusion_test.go, pkg/parser/parser.go, pkg/parser/parser.peg, pkg/renderer/html5/file_inclusion_test.go, pkg/types/types.go, pkg/types/types_test.go, test/includes/include.foo, testsupport/preflight_document_matcher.go
do not process 'include' macros in non-asciidoc files that are included
in the parent document.
also, move the 'IsAsciidoc' func from 'types' to 'parser' pkg.
fixes #380
=> feat(parser): do not further processing inclusions in non-asciidoc files

Makefile, pkg/parser/blank_line_test.go, pkg/parser/comment_test.go, pkg/parser/cross_reference_test.go, pkg/parser/delimited_block_test.go, pkg/parser/document_preprocessing.go, pkg/parser/document_processing.go, pkg/parser/element_attributes_test.go, pkg/parser/file_inclusion.go, pkg/parser/file_inclusion_test.go, pkg/parser/footnote_test.go, pkg/parser/frontmatter_test.go, pkg/parser/image_test.go, pkg/parser/labeled_list_test.go, pkg/parser/link_test.go, pkg/parser/literal_block_test.go, pkg/parser/ordered_list_test.go, pkg/parser/paragraph_test.go, pkg/parser/parser.go, pkg/parser/parser.peg, pkg/parser/passthrough_test.go, pkg/parser/quoted_text_test.go, pkg/parser/section_test.go, pkg/parser/unordered_list_test.go, pkg/types/types.go, testsupport/console_matcher_test.go, testsupport/matcher_options.go, testsupport/preflight_document_matcher.go, testsupport/preflight_document_matcher_test.go
and apply the same change to variables, etc.
Fixes #435
=> refactor(parser): rename 'PreflightDocument' to 'DraftDocument'

libasciidoc_test.go, pkg/parser/document_preprocessing.go, pkg/parser/file_inclusion.go, pkg/parser/file_inclusion_test.go, pkg/renderer/html5/file_inclusion_test.go, pkg/types/types.go, test/includes/child-include.adoc, test/includes/grandchild-include.adoc, test/includes/parent-include-offset.adoc
Uses a func type to proceed with the cumulated level offsets,
which should pave the road to support absolute level offsets, too.
Fixes #434
=> feat(parser): support nested relative level offset in file inclusions

pkg/parser/check_list_test.go, pkg/parser/comment_test.go, pkg/parser/cross_reference_test.go, pkg/parser/delimited_block_test.go, pkg/parser/document_attributes_test.go, pkg/parser/element_attributes_test.go, pkg/parser/file_inclusion_test.go, pkg/parser/footnote_test.go, pkg/parser/frontmatter_test.go, pkg/parser/image_test.go, pkg/parser/inline_elements_test.go, pkg/parser/labeled_list_test.go, pkg/parser/link_test.go, pkg/parser/literal_block_test.go, pkg/parser/mixed_lists_test.go, pkg/parser/ordered_list_test.go, pkg/parser/paragraph_test.go, pkg/parser/passthrough_test.go, pkg/parser/q_a_list_test.go, pkg/parser/quoted_text_test.go, pkg/parser/section_test.go, pkg/parser/table_test.go, pkg/parser/unordered_list_test.go, pkg/parser/user_macro_test.go, testsupport/document_block_matcher.go, testsupport/document_block_matcher_test.go, testsupport/document_matcher.go, testsupport/document_matcher_test.go, testsupport/draft_document_matcher.go, testsupport/draft_document_matcher_test.go
=> refactor(test): rename `Equal...` to `Become...` matchers

pkg/parser/link_test.go, pkg/parser/parser.go, pkg/parser/parser.peg
Missing stop when a space is encountered, which may happen
when en external link without brackets is in the middle of a
sentence.
Fixes #442
=> fix(parser): invalid parsing of link location

Makefile, pkg/parser/document_attributes_test.go, pkg/parser/document_preprocessing.go, pkg/parser/document_processing.go, pkg/parser/file_inclusion.go, pkg/parser/link_test.go, pkg/parser/parser.go, pkg/parser/parser.peg, pkg/renderer/html5/document.go, pkg/renderer/html5/link_test.go, pkg/types/types.go, pkg/types/types_test.go, testsupport/console_matcher.go, testsupport/draft_document_matcher.go
support the whole link as a document attribute (or vice versa?).
to do so:
- apply the document attribute substitutions during the document
processing
- then reparse the paragraph line (if needed) to look for inline links
Fixes #351
=> feat(parser): support document attributes in links

pkg/parser/document_preprocessing.go, pkg/parser/document_processing.go, pkg/parser/file_inclusion_test.go, pkg/parser/image_test.go, pkg/parser/link_test.go, pkg/parser/predefined_attributes_test.go, pkg/renderer/html5/link_test.go, pkg/types/types.go, pkg/types/types_test.go
get the "document attributes" by reading the beginning of the
first blocks of the draft document, and use them while processing
the section 0 title.
Fixes #447
=> feat(parser): include document attribute when processing section 0

pkg/parser/document_processing.go, pkg/parser/document_processing_apply_substitutions.go, pkg/parser/document_processing_apply_substitutions_test.go, pkg/parser/parser.go, pkg/parser/parser.peg
only parse for inline links if a document attribute
subsitution occurred
also, update the grammar for inline links to parse
until the EOF
Fixes #462
=> refactor(parser): do not parse for links if not needed

LIMITATIONS.adoc, pkg/parser/link_test.go, pkg/parser/parser.go, pkg/parser/parser.peg, pkg/types/types.go, testsupport/document_matcher.go
provide a support with workaround: need to set the `[]` explicitly
if the URL ends with `_` or `*` when wrapped in italic or bold quotes
also, allow for document attribute substitutions in quoted text
fixes #456
=> fix(parser): support inline links in quoted text

Makefile, pkg/parser/document_processing_rearrange_lists.go, pkg/parser/document_processing_rearrange_lists_test.go, pkg/parser/labeled_list_test.go, pkg/parser/mixed_lists_test.go, pkg/parser/parser.go, pkg/parser/parser.peg, pkg/parser/q_a_list_test.go, pkg/renderer/html5/labeled_list.go, pkg/renderer/html5/labeled_list_test.go, pkg/types/types.go
Modify the grammar to include a new rule to parse the labeled list item term to find footnotes, images, links and quoted text, but only when processing the draft document into the final document. The draft document will still have a "raw" string term, to keep the parsing of the whole document fast.
Fixes #456
Fixes #460
=> feat(parser/renderer): support rich content in labeled list item terms

libasciidoc.go, libasciidoc_test.go, pkg/renderer/options.go, testsupport/html5_rendering_matcher.go
use file's mtime instead of `time.Now()`
Fixes #461
=> fix(renderer): use file mtime as 'Last updated'

cmd/libasciidoc/root_cmd.go, libasciidoc.go, pkg/parser/bench_test.go, pkg/parser/cross_reference_test.go, pkg/parser/document_processing_apply_substitutions.go, pkg/parser/parser.go, pkg/parser/parser.peg, pkg/renderer/html5/cross_reference.go, pkg/renderer/html5/cross_reference_test.go, pkg/renderer/html5/html5.go, pkg/types/types.go
support the `xref` inline macro
also, delete the unwanted `-s` file in the repo!
Fixes #459
=> feat(parser/renderer): support external cross references

pkg/parser/delimited_block_test.go, pkg/parser/parser.go, pkg/parser/parser.peg, pkg/renderer/html5/delimited_block.go, pkg/renderer/html5/delimited_block_test.go
change the parser rules to identify the blank lines and skip them
during rendering when there is nothing else afterwards
fixes #470
=> fix(parser/renderer): skip trailing empty lines in delimited blocks

pkg/parser/concealed_index_terms_test.go, pkg/parser/document_processing_filter_blocks.go, pkg/parser/parser.go, pkg/parser/parser.peg, pkg/renderer/html5/concealed_index_term_test.go, pkg/types/types.go
support the `(((` syntax in paragraphs, but discard
the element from the final document, so no rendering
is done.
Fixes #473
=> feat(parser): support concealed index terms

pkg/parser/document_processing_apply_substitutions.go, pkg/parser/inline_elements_test.go, pkg/parser/parser.go, pkg/parser/parser.peg, pkg/types/types.go, pkg/types/types_utils.go, pkg/types/types_utils_test.go
remove unused variable assignations in the rules
use the 'types.Merge' func to merge all elements
when initializing the quoted texts.
Fixes #476
=> refactor(parser): simplify quoted text rules

.travis.yml, cmd/libasciidoc/root_cmd.go, libasciidoc_test.go, pkg/renderer/html5/document.go, pkg/renderer/html5/document_test.go, pkg/renderer/options.go, testsupport/html5_rendering_matcher.go
when the `--css=...` argument is used, the generated HTML
document contains a `<link type="text/html" rel="stylesheet" href="...">`
element with the given `--css` value.
Fixes #482
=> feat(cli): add 'css' arg to specify the stylesheet

pkg/parser/document_attributes_test.go, pkg/parser/parser.go, pkg/parser/parser.peg
support comments (single lines and blocks) before the author
and between the author and the revision
Fixes #481
=> fix(parser): support comment between doc title and author

pkg/parser/labeled_list_test.go, pkg/parser/parser.go, pkg/parser/parser.peg, pkg/renderer/html5/labeled_list_test.go
fixing 'ContinuedListItemElement' rule to support
a document blocks which include 'ContinuedParagraph' blocks
instead of regular 'Paragraph' blocks
Fixes #492
=> fix(parser): support chained admonitions

pkg/parser/paragraph_test.go, pkg/parser/parser.go, pkg/parser/parser.peg, pkg/parser/quoted_text_test.go, testsupport/parse_document_block.go, testsupport/parse_draft_document.go
Refactored grammar to support the following content:
```
non_italic_content _italic content_
```
where only `italic content` is parsed
as quoted text
Fixes #504
=> fix(parser): fix quoted text delimitation

pkg/parser/index_terms_test.go, pkg/parser/parser.go, pkg/parser/parser.peg, pkg/renderer/html5/index_term.go, pkg/renderer/html5/index_terms_test.go, testsupport/render_html5.go
Modify IndexTermContent rule to match non-alphanums which
may not be used as quoted text delimters
Also, fix index term renderer (use the `renderInlineElements`
func to avoid having `\n` between each term element
Fixes #503
=> fix(parser/renderer): support non-alphanum characters in index terms

cmd/libasciidoc/root_cmd.go, pkg/parser/document_processing_filter_blocks.go, pkg/parser/document_processing_filter_blocks_test.go, pkg/parser/index_terms_test.go, pkg/renderer/html5/elements.go, pkg/renderer/html5/index_term.go, pkg/renderer/html5/index_terms_test.go, pkg/renderer/html5/inline_elements.go, pkg/renderer/html5/section.go
do not exclude ConceledIndexTerms (and Blanklines)
in final document, but silently ignore them in the  HTML rendering phase.
also, do not print help when an error occurs when running from CLI
Fixes #502
=> fix(parser/renderer): support concelead index terms in labeled lists

pkg/renderer/html5/document_details_test.go, pkg/renderer/html5/html5.go, testsupport/html5_template_matcher.go
when the `noheader` or `nofooter` document attributes
are set (with an empty value), the header and footer
are NOT rendered (respectively)
Fixes #510
=> feat(renderer): attribute to disable header and footer

libasciidoc_test.go, pkg/renderer/html5/blank_line_test.go, pkg/renderer/html5/comment_test.go, pkg/renderer/html5/cross_reference_test.go, pkg/renderer/html5/delimited_block_test.go, pkg/renderer/html5/distinct_lists_test.go, pkg/renderer/html5/document_details_test.go, pkg/renderer/html5/file_inclusion_test.go, pkg/renderer/html5/footnote_test.go, pkg/renderer/html5/html5_test.go, pkg/renderer/html5/image_test.go, pkg/renderer/html5/index_terms_test.go, pkg/renderer/html5/labeled_list_test.go, pkg/renderer/html5/link_test.go, pkg/renderer/html5/literal_block_test.go, pkg/renderer/html5/ordered_list_test.go, pkg/renderer/html5/paragraph_test.go, pkg/renderer/html5/passthrough_test.go, pkg/renderer/html5/quoted_text_test.go, pkg/renderer/html5/section_test.go, pkg/renderer/html5/string_test.go, pkg/renderer/html5/table_of_contents_test.go, pkg/renderer/html5/table_test.go, pkg/renderer/html5/unordered_list_test.go, pkg/renderer/html5/user_macro_test.go, testsupport/render_html5.go, testsupport/render_html5_test.go
rename to RenderHTML since the matcher can also
render full HTML documents.
Fixes #523
=> refactor(test): rename RenderHTML5Body matcher

pkg/renderer/html5/string.go, pkg/renderer/html5/string_test.go
replace `(C)` with `&#169;`
Fixes #524
=> feat(renderer): support Copyright character replacement

pkg/parser/blank_line_test.go, pkg/parser/check_list_test.go, pkg/parser/comment_test.go, pkg/parser/cross_reference_test.go, pkg/parser/delimited_block_test.go, pkg/parser/document_attributes_test.go, pkg/parser/document_processing_test.go, pkg/parser/element_attributes_test.go, pkg/parser/file_inclusion_test.go, pkg/parser/footnote_test.go, pkg/parser/frontmatter_test.go, pkg/parser/image_test.go, pkg/parser/index_terms_test.go, pkg/parser/labeled_list_test.go, pkg/parser/link_test.go, pkg/parser/literal_block_test.go, pkg/parser/mixed_lists_test.go, pkg/parser/ordered_list_test.go, pkg/parser/paragraph_test.go, pkg/parser/q_a_list_test.go, pkg/parser/quoted_text_test.go, pkg/parser/section_test.go, pkg/parser/unordered_list_test.go, testsupport/document_matcher.go, testsupport/document_matcher_test.go, testsupport/draft_document_matcher.go, testsupport/draft_document_matcher_test.go
Create custom Gomega matchers for Document and DraftDocument
Use go-spew and go-diff to provide meaningfull failure messages
when the actual value does not match the expectation
Fixes #536
=> refactor(test): add document matchers

pkg/parser/document_processing.go, pkg/parser/document_processing_rearrange_sections.go, pkg/parser/document_processing_rearrange_sections_test.go, pkg/renderer/html5/elements.go, pkg/renderer/html5/footnote_reference.go, pkg/renderer/html5/image.go, pkg/renderer/html5/index_term.go, pkg/renderer/html5/table_of_contents.go
Address errors reported by `golangci-lint ./...`
Fixes #541
=> refactor(parser/renderer): address golangci errors

libasciidoc_test.go, pkg/renderer/html5/document_details_test.go, pkg/renderer/html5/html5.go, pkg/renderer/html5/html5_test.go, pkg/types/document_attributes.go
Include authors (semicolon-separated list) in a
`<meta name="author">` tag in the document head
Fixes #543
=> feat(renderer): include authors in 'meta' tag

.golangci.yml, libasciidoc.go, libasciidoc_test.go, pkg/configuration/configuration.go, pkg/parser/document_processing.go, pkg/renderer/html5/document_details.go, pkg/renderer/html5/html5.go, pkg/renderer/html5/html5_test.go, pkg/validator/validator.go, pkg/validator/validator_suite_test.go, pkg/validator/validator_test.go
Add a new `pkg/validator` package which validates
the given document, reports problems and in the case
of a `manpage` document, changes the doctype to `article`
if a problem was found.
Fixes #529
=> feat(validator): validate manpage document

pkg/parser/section_test.go
verify that the preamble does not contain
the blankline that follows the document
attribute declaration after the document
title.
Bug could not be reproduced, as tests show.
Fixes #301
=> test(parser): verify preamble/blankline

.github/workflows/ci-build.yml, Makefile
Use `actions/setup-go@v2` so that installed tools are available in `PATH`
Fixes #518
=> chore(build): build on Windows with GitHub Actions

make/go.mk, pkg/parser/parser.go, pkg/parser/parser.peg
Remove 'InlineElementsWithoutSubtitution' from the grammar
and the generate goal
Fixes #555
=> chore(parser): remove unused rule

libasciidoc_test.go, pkg/renderer/html5/delimited_block_test.go, pkg/renderer/html5/file_inclusion_test.go, pkg/renderer/html5/html5_test.go, pkg/renderer/html5/html_escape.go, pkg/renderer/html5/labeled_list_test.go, pkg/renderer/html5/ordered_list_test.go, pkg/renderer/html5/paragraph_test.go, test/fixtures/supported/lists.html, test/fixtures/supported/sample.html
No need to replace `'` and `"` with `&#39;` and `&#34;`.
Fixes #565
=> refactor(renderer): discard quote replacement in HTML

pkg/renderer/html5/delimited_block_test.go, pkg/types/types.go
=> fix(types): `CalloutListItem` must implement `DocumentElement`

pkg/renderer/html5/delimited_block.go, pkg/renderer/html5/delimited_block_test.go
remove call to `escape` on the content of the source block
Fixes #570
=> fix(renderer): do not HTML escape content twice in source blocks

pkg/parser/delimited_block_test.go, pkg/parser/document_preprocessing.go, pkg/parser/file_inclusion_test.go, pkg/parser/paragraph_test.go, pkg/parser/parser.go, pkg/parser/parser.peg, pkg/parser/passthrough_test.go, pkg/parser/quoted_text_test.go, pkg/renderer/html5/delimited_block.go, pkg/renderer/html5/delimited_block_test.go, pkg/renderer/html5/elements.go, pkg/renderer/html5/passthrough.go, pkg/renderer/html5/passthrough_test.go, pkg/types/element_attributes.go, pkg/types/types.go
includes delimited blocks (with `++++`) and
open blocks with `[pass]`
Fixes #269 - Support passthrough blocks
=> feat(parser/renderer): support passthrough blocks

make/bench.mk
setting an iteration count instead of letting the benchmark
toolo decided how many iterations are enough.
This will allow for better comparisons of proposed changes
Fixes #575
=> chore(build): set iteration count on benchmarks (100x)

pkg/renderer/html5/string.go, pkg/renderer/html5/string_test.go
This adds trademark and registered trademark symbols.
I thought about adding support for the single and double arrows and emdash substitutions as well, but those are harder.
The arrows contain < and > and need to parsed and replaced before the &gt; and &lt; entities get substituted (so order of parsing is a problem).  The emdash actually needs a little context as well, as it only gets replaced when it is flanked appropriately, and it also can cause spaces to get replaced with thin spaces if it is flanked by spaces on both sides.
=> Add support for (TM) and (R) in markup.

pkg/renderer/html5/html5.go, pkg/renderer/html5/html5_test.go
This adds support for setting the role on a level 0 title,
which will cause the class for the document body to be set.
=> feat(renderer): role not honored on h1 titles (#583)

.github/workflows/ci-build.yml, .gitignore, make/bench.mk, make/profile.mk
Create a separate `profile` target for profiling. Only run the
benchmarks once in this target.
Update `bench` target to make five passes and save the output to a file
for use with `benchstat`.
Add a `bench-smoke` target to smoke test the top-level benchmarks by
running them only once.  This target is run via CI to ensure that the
benchmarks are functional.
Fixes #580
=> Refactor bench and profile make targets

pkg/parser/parser.go, pkg/parser/parser.peg, pkg/parser/quoted_text_test.go, pkg/renderer/sgml/element_role.go, pkg/renderer/sgml/html5/quoted_text.go, pkg/renderer/sgml/html5/quoted_text_test.go, pkg/renderer/sgml/quoted_text.go, pkg/types/attributes.go, pkg/types/types.go
This adds support for both `[role]` and `[.role#id]`
style attributes on quoted text blocks.
Fixes #588
(Btw, I wrote a bunch of test cases for this in the HTML tree, and added code to make these replacements "safe" (HTML escaped), but I did *not* add tests to the parser side.  Hope that's ok.)
=> feat(parser/renderer): Support inline role assignment

pkg/parser/parser.go, pkg/parser/parser.peg, pkg/parser/quoted_text_test.go, pkg/renderer/sgml/html5/quoted_text.go, pkg/renderer/sgml/html5/quoted_text_test.go, pkg/renderer/sgml/html5/templates.go, pkg/renderer/sgml/quoted_text.go, pkg/renderer/sgml/sgml_renderer.go, pkg/renderer/sgml/templates.go, pkg/types/types.go
This is built upon my PR for #588, and depend on those changes.  It implements #mark support.
Reviewers should only look at the last PR, which will be rebased once #588 is merged.
This supports using the role to change the <mark> into a <span> with the class set appropriate, giving much flexibility to adding custom styling to regions of text.
This fixes #599
=> 599 Support for #mark 

pkg/parser/document_processing_filter_blocks.go, pkg/parser/document_test.go, pkg/parser/element_attributes_test.go, pkg/parser/parser.go, pkg/parser/parser.peg
the draft document contains the attributes, but they
are filtered out when processing it.
Fixes #605 - Error when parsing doc containing only an attribute
=> fix(parser): ignore standalone attributes at the end of doc

pkg/parser/parser.go, pkg/parser/parser.peg, pkg/parser/quoted_string_test.go, pkg/renderer/sgml/elements.go, pkg/renderer/sgml/html5/quoted_string_test.go, pkg/renderer/sgml/string.go, pkg/types/types.go
This adds support for the "`double`" and '`single`' types of
quoted strings.  These are inline enclosed elements, which is
necessary to prevent confusion with code blocks.  It also
matches asciidoctor.
Fixes #620
(PR NOTE: I did find a few bugs in the asciidoctor parser here; I have not attempted to be 100% bug compatible with asciidoctor.  This does conform to the documented, and what I believe, intended syntax was.  The PR is big mostly because of the large number of tests.  I will be following up with a fix for #176 once this PR integrates -- this PR is a bit more important to me than #176 as the fallback rendering for #176 is arguably still reasonable, but the fallback for this is not and quite ugly.)
=> feat(parser/render) Support typographic quote marks

pkg/parser/parser.go, pkg/parser/parser.peg, pkg/parser/quoted_text_test.go, pkg/renderer/sgml/html5/quoted_text_test.go
Quoted texts (such as bold) should span newlines, but should
not be permitted to span paragraphs or blocks.  This fixes
all of them, and includes parser and renderer validation.
Fixes #623
=> fix(parser): quoted text newline handling

pkg/parser/parser.go, pkg/parser/parser.peg
This simplifies the grammar slightly.  May also improve the
performance.
Fixes #631
=> refactor(parser): quoted text doesn't need !`\`

pkg/parser/parser.go, pkg/parser/parser.peg, pkg/parser/quoted_string_test.go, pkg/renderer/sgml/xhtml5/quoted_string_test.go
This doesn't catch all the ways that quoted strings should be treated
as constrained quoted text, but does fix this non-pathological test,
with fixed test cases.
Fixes #622
=> bug(parser): quoted strings should not allow interior adjacent spaces

pkg/renderer/sgml/html5/string_test.go, pkg/renderer/sgml/string.go, pkg/renderer/sgml/xhtml5/string_test.go
We were using the code 153, which is not the same value used by
asciidoctor, and doesn't uniformly render as the trademark
symbol.
Fixes #641
(This PR should be mergeable/rebaseable as is, because it's changes are fairly isolated from other PRs currently outstanding.)
=> bug(renderer): Wrong code for (TM)

pkg/renderer/sgml/callout_list.go, pkg/renderer/sgml/delimited_block.go, pkg/renderer/sgml/html5/callout_list.go, pkg/renderer/sgml/html5/delimited_block.go, pkg/renderer/sgml/html5/html5.go, pkg/renderer/sgml/html5/image.go, pkg/renderer/sgml/html5/labeled_list.go, pkg/renderer/sgml/html5/literal_blocks.go, pkg/renderer/sgml/html5/ordered_list.go, pkg/renderer/sgml/html5/paragraph.go, pkg/renderer/sgml/html5/table.go, pkg/renderer/sgml/html5/unordered_list.go, pkg/renderer/sgml/html_escape.go, pkg/renderer/sgml/image.go, pkg/renderer/sgml/labeled_list.go, pkg/renderer/sgml/literal_blocks.go, pkg/renderer/sgml/ordered_list.go, pkg/renderer/sgml/paragraph.go, pkg/renderer/sgml/renderer.go, pkg/renderer/sgml/table.go, pkg/renderer/sgml/unordered_list.go, pkg/renderer/sgml/xhtml5/delimited_block.go, pkg/renderer/sgml/xhtml5/image.go, pkg/renderer/sgml/xhtml5/paragraph.go, pkg/renderer/sgml/xhtml5/table.go, pkg/renderer/sgml/xhtml5/xhtml5.go
This eliminates the needs for templates to call escape.
Fixes #640
=> refactor(renderer): Clean up/simplify title handling

libasciidoc_test.go, pkg/renderer/sgml/html5/delimited_block_test.go, pkg/renderer/sgml/html5/file_inclusion_test.go, pkg/renderer/sgml/html5/html5_test.go, pkg/renderer/sgml/html5/labeled_list_test.go, pkg/renderer/sgml/html5/ordered_list_test.go, pkg/renderer/sgml/html5/paragraph_test.go, pkg/renderer/sgml/html5/quoted_string_test.go, pkg/renderer/sgml/html_escape.go, pkg/renderer/sgml/xhtml5/delimited_block_test.go, pkg/renderer/sgml/xhtml5/file_inclusion_test.go, pkg/renderer/sgml/xhtml5/labeled_list_test.go, pkg/renderer/sgml/xhtml5/ordered_list_test.go, pkg/renderer/sgml/xhtml5/paragraph_test.go, pkg/renderer/sgml/xhtml5/quoted_string_test.go, pkg/renderer/sgml/xhtml5/xhtml5_test.go, test/fixtures/supported/basic.html, test/fixtures/supported/lists.html, test/fixtures/supported/sample.html
This makes all single and double quotes escaped in SGML content,
improving the safety of using these characters inline.
Fixes #644
=> feature(renderer): htmlEscape should escape quotes

.github/workflows/ci-build.yml
This uses https://github.com/actions/cache to speed up builds.
Fixes #591
=> chore(build): Use https://github.com/actions/cache

libasciidoc_test.go, pkg/parser/document_processing_test.go, pkg/parser/image_test.go, pkg/parser/parser.go, pkg/parser/parser.peg, pkg/parser/quoted_string_test.go, pkg/parser/quoted_text_test.go, pkg/parser/unordered_list_test.go, pkg/renderer/sgml/html5/html5_test.go, pkg/renderer/sgml/html5/quoted_string_test.go, pkg/renderer/sgml/html5/quoted_text_test.go, pkg/renderer/sgml/html5/string_test.go, pkg/renderer/sgml/string.go, pkg/renderer/sgml/xhtml5/quoted_string_test.go, pkg/renderer/sgml/xhtml5/string_test.go, pkg/renderer/sgml/xhtml5/xhtml5_test.go, test/fixtures/supported/lists.html
This provides support for both explicit typographical quotes, and
the implicit curved apostrophe when it appears between letters
as in mother's day.
This also refactors the handling of certain typographic symbols,
moving their handing from the render to the parser, so that they
are treated properly during the parse phase.  (This was important
in properly handling these curved quotes.)
Also, the greedy rules for string elements in quoted text were
removed, as they were interfering with the parse, and not strictly
required.  (They were an optimization.)  It's our opinion that for
most documents quoted text will be in the minority, such that
the performance gain provided by the old rules was minimal at best.
This PR is based upon the work submitted for #644 (PR #647) and should be rebased …
=> feature(parser/renderer): Render curved quotes

pkg/parser/labeled_list_test.go, pkg/parser/paragraph_test.go, pkg/parser/parser.go, pkg/parser/parser.peg, pkg/parser/q_a_list_test.go, pkg/renderer/sgml/html5/labeled_list_test.go, pkg/renderer/sgml/labeled_list.go, pkg/renderer/sgml/paragraph.go, pkg/renderer/sgml/xhtml5/labeled_list_test.go, pkg/types/attributes.go
This PR represents an incremental improvement towards addressing
the support for multiple roles.  Using shorthand syntax without
any positional items, all block elements can now support multiple
roles.
The labeled lists fully support using the positional attribute
as the style, using simpler syntax.  Eventually all blocks will
convert to using the BlockAttr rule; conversion and testing for
each of them will be submitted individually.
For this reason, only the simple paragraph and labeled lists
tests include testing for multiple roles so far.  More tests
will be added as we convert elements to use the simpler common
BlockAttrs rule.
(NB: It's my hope that this PR will set the stage for follow-ups, which should then be easier to review.)
=> refactor(parser): Refactor shorthand attrs and labeled lists

pkg/parser/parser.go, pkg/parser/parser.peg, pkg/parser/unordered_list_test.go, pkg/renderer/sgml/element_style.go, pkg/renderer/sgml/html5/unordered_list.go, pkg/renderer/sgml/html5/unordered_list_test.go, pkg/renderer/sgml/unordered_list.go, pkg/renderer/sgml/xhtml5/unordered_list_test.go
This converts unordered lists so that they can support multiple
roles, and the style attribute properly.  It includes both the
parser side and renderer side changes.  The templates were
converted to use the exact HTML output that asciidoctor emits.
Fixes #658
=> feature(parser/renderer): unordered lists should support style

pkg/parser/document_processing_rearrange_lists.go, pkg/parser/document_processing_rearrange_lists_test.go, pkg/parser/element_attributes_test.go, pkg/parser/labeled_list_test.go, pkg/parser/mixed_lists_test.go, pkg/parser/ordered_list_test.go, pkg/parser/paragraph_test.go, pkg/parser/parser.go, pkg/parser/parser.peg, pkg/renderer/sgml/html5/ordered_list.go, pkg/renderer/sgml/ordered_list.go, pkg/types/attributes.go, pkg/types/types.go
This adds support for the multiple role markup to unordered
lists.  This also cleans up the NumberingStyle, using just the
normal Style attribute.
Finally a subtle bug was fixed in the parser for dealing
with PositionalValues, which we had to fix here in order to
pass the various tests for ordered lists.
There are also a few more tests added to cover that case, in
other areas, written while diagnosing that bug.
=> refactor(parser): Refactor ordered lists for multiple roles

pkg/parser/parser.go, pkg/parser/parser.peg, pkg/parser/table_test.go
This adds the multiple roles supports (and options) for tables.
This is parser side only at this point.  More work coming in the render to enable the tables to support some of these options.
This is built on top of PR #661 -- the last commit in this PR should rebase cleanly on top of master once PR #661 is merged.
=> Table attribute refactoring

pkg/parser/parser.go, pkg/parser/parser.peg, pkg/types/types.go
The code for quote blocks already switches to verse block if
the [verse] attribute is present, thus there is no need for
extra parsing steps to attempt to distinguish verses.  This
reduces complexity, and should provide a small performanc boost.
=> refactor(parser): VerseBlock is redundant

pkg/parser/parser.go, pkg/parser/parser.peg, pkg/renderer/sgml/html5/ordered_list.go, pkg/renderer/sgml/html5/ordered_list_test.go, pkg/renderer/sgml/ordered_list.go, pkg/renderer/sgml/xhtml5/ordered_list_test.go
While testing, found some more potential edge cases around
the parser for attributes lists, so tightened those up.
Fixes #662
=> feature(renderer): Support reversed lists

pkg/parser/paragraph_test.go, pkg/parser/parser.go, pkg/parser/parser.peg, pkg/renderer/sgml/html5/image.go, pkg/renderer/sgml/html5/image_test.go, pkg/renderer/sgml/html5/paragraph_test.go, pkg/renderer/sgml/image.go, pkg/renderer/sgml/xhtml5/image.go, pkg/renderer/sgml/xhtml5/paragraph_test.go, pkg/types/attributes.go, pkg/types/types.go
This also includes bug fixes for parser.  We've tried to
emulate most, but not all, of the quirks found in asciidoctor
with respect to images.
(Following commentary not in the git log:)
This PR refactors (and removes) some of the logic intended to make verseblocks and quoteblocks work like asciidoctor.  Apparently asciidoctor treats [quote] differently from [verse] when process image blocks.  Both of these cases are actually pathological, since imageblocks should never be the content of a verse or a quote (the result was actually undesirable as well -- leaving source markup in the output).  In order to bring some sanity, we treat them both the same, and assume that any attributes ahead of an image:: block really are meant to apply to the image.
We also noted that the handling for inline …
=> feature(parser/render): Multiple roles for images.

pkg/parser/parser.go, pkg/parser/parser.peg, pkg/renderer/sgml/html5/html5.go, pkg/renderer/sgml/html5/html5_test.go, pkg/renderer/sgml/html5/section.go, pkg/renderer/sgml/html5/section_test.go, pkg/renderer/sgml/renderer.go, pkg/renderer/sgml/section.go, pkg/renderer/sgml/xhtml5/section_test.go, pkg/renderer/sgml/xhtml5/xhtml5.go, pkg/renderer/sgml/xhtml5/xhtml5_test.go
This adds support for both sections and the top-level document
(section0 elements) to have multiple roles.  It also adds the
support for the ID element for documents, in a way that precisely
emulates what asciidoctor does (only custom IDs are emitted).
=> refactor(parser/renderer): Support section and document roles

pkg/parser/parser.go, pkg/parser/parser.peg, pkg/types/attributes.go, pkg/types/types.go
This changes NewNamedElementAttributes to be a varargs style
function, simplifying use, and allows us to eliminate the
special function used for alloction icon attributes.
While here, removed an unused parser rule.
=> refactor(parser): Minor refactoring of icon attributes

pkg/parser/attributes_test.go, pkg/parser/parser.go, pkg/parser/parser.peg, pkg/types/types.go
(Note that block attributes, and some other inline attributes,
suffer from this problem -- this PR only fixes icon and image
inline attributes.)
While working on some new support for align and float attributes,
we noticed that the parser was fragile, and failed on certain
cases including double embedded whitespace, embedded quote marks,
and others.
This logic will be expanded to other elements and to block
attributes; this incremental PR should be easier to review.
=> bug(parser): Inline attribute parsing is incorrect

LIMITATIONS.adoc, pkg/renderer/sgml/element_role.go, pkg/renderer/sgml/html5/image.go, pkg/renderer/sgml/html5/image_test.go, pkg/renderer/sgml/html5/templates.go, pkg/renderer/sgml/image.go, pkg/renderer/sgml/sgml_renderer.go, pkg/renderer/sgml/templates.go, pkg/renderer/sgml/xhtml5/image.go, pkg/renderer/sgml/xhtml5/image_test.go, pkg/types/attributes.go
Note that the global figure-caption override is still not honored.
(Text below is not in the git history).
I have changes to support figure-caption, but they require adding new default attributes at document root.  This will require updating ever test in the parser suite -- > 350 when I looked -- to add these stock attributes.  As this is going to be such a large job, I'd rather not do it multiple times as we add other global caption attributes (e.g. for TIP, CAUTION, and Example blocks, etc.)   Instead I'd like to do those later, all at once.   Unless someone has a better idea how to deal with "unsetting" default attributes (i.e. the main use of figure-caption is in a disable -- :figure-caption!:  block.
=> feature(renderer): Add image float, align, and capture support.

README.adoc, pkg/parser/attributes_test.go, pkg/parser/icon_test.go, pkg/parser/image_test.go, pkg/parser/paragraph_test.go, pkg/parser/parser.go, pkg/parser/parser.peg, pkg/renderer/sgml/element_role.go, pkg/renderer/sgml/html5/table.go, pkg/renderer/sgml/html5/table_test.go, pkg/renderer/sgml/icon.go, pkg/renderer/sgml/image.go, pkg/renderer/sgml/table.go, pkg/renderer/sgml/xhtml5/table.go, pkg/renderer/sgml/xhtml5/table_test.go, pkg/types/attributes.go, pkg/types/types.go
This provides top-level support for attributes to style the
entire table (frame, grid, float, stripes, width, autowidth).
The cols attribute is still not handled, meaning that it is
still not possible to configure column widths.
=> feature(renderer): Top level table styling

pkg/parser/document_attributes_test.go, pkg/parser/document_processing_apply_substitutions.go, pkg/parser/link_test.go, pkg/renderer/sgml/document_details.go, pkg/renderer/sgml/html5/document_details.go, pkg/renderer/sgml/xhtml5/document_details.go, pkg/renderer/sgml/xhtml5/document_details_test.go, pkg/types/attributes.go, pkg/types/document_attributes_overrides.go, pkg/types/predefined_attributes.go, pkg/types/types.go
This supports the version-label be changed, or even reset
for document attributes.
To support resetting this label, the initial value is located
in the Predefined attributes, and a reset of the attribute is
stored as a nil attribute value instead of deleting it from the
attributes.  This allows us to distinguish a reset as an override.
This approach will be used for other predefined text values in
follow ups.
Fixes #710
=> feature(renderer): version-label not honored

pkg/renderer/sgml/document_details.go
A printf message used during testing accidentally was left in
the commit submitted for 711.  This removes that.
(Sorry, I should have caught this before the PR was submitted!)
=> bug(renderer): Remove stray debugging message

LIMITATIONS.adoc, README.adoc, pkg/renderer/sgml/delimited_block.go, pkg/renderer/sgml/html5/delimited_block_test.go, pkg/renderer/sgml/html5/paragraph.go, pkg/renderer/sgml/html5/paragraph_test.go, pkg/renderer/sgml/html5/templates.go, pkg/renderer/sgml/paragraph.go, pkg/renderer/sgml/sgml_renderer.go, pkg/renderer/sgml/templates.go, pkg/renderer/sgml/xhtml5/delimited_block_test.go, pkg/renderer/sgml/xhtml5/paragraph_test.go
This fixes three separate issues (it was natural to fix them all
at the same time).
Fixes #719 Should not panic on unrecognized source language
Fixes #706 Support "Chroma" as a syntax highlighter choice
Fixes #704 Source paragraph does not honor syntax highlighter
=> feature/bug(renderer): Support chroma, fix source paragraph

pkg/renderer/sgml/html5/table.go, pkg/renderer/sgml/html5/templates.go, pkg/renderer/sgml/sgml_renderer.go, pkg/renderer/sgml/table.go, pkg/renderer/sgml/templates.go, pkg/renderer/sgml/xhtml5/table_test.go, pkg/types/attributes.go, pkg/types/predefined_attributes.go, pkg/types/types_utils.go
This uses a kind of hack to make Table captions work mostly as
they are documented to, so that {counter:table-number} seems to
act like a substitution.  This hack should be removed when full
attribute value substitution is done.  (This approach has the
benefit of localizing this hack until it can be replaced.)
Of course, this will be incompatible with other uses of the
table-counter counter (because it isn't actually the same counter),
and won't support anything beyond the most trivial substitutions.
While here removed a couple of unused functions.
Fixes #712
=> feature(renderer): Tables should honor table-caption attribute

pkg/parser/icon_test.go, pkg/types/non_alphanumerics_replacement.go
Fixes #691
(This also honors alt if its set on the icon, and uses that instead of the icon class).
=> bug(renderer): Section ID should include the icon class

.github/workflows/ci-build.yml, go.mod, go.sum, make/go.mk, pkg/parser/parser.go
This will ensure that a PR includes the optimized
parser when running on CI
Fixes #732
=> chore(build): run 'verify-parser' goal on CI

CONTRIBUTE.adoc, README.adoc, make/go.mk, pkg/parser/generate.go
chore(build): Use go generate
This provides a simpler go generate (meaning developers no longer
need to use "make", which is a qualify of life improvement for
developers working on non-UNIX systems), and updates the instructions
to reflect the trivial installation steps.  (Also details about using
go generate for developers are added to the CONTRIBUTING document.)
This also coincidentally includes updates to the latest dependencies,
which has the benefit of eliminating the protobuf dependency.
Fixes https://github.com/bytesparadise/libasciidoc/issues/638
=> chore(docs): Update the installation instructions

pkg/parser/document_processing_apply_substitutions.go, pkg/parser/paragraph_test.go
=> bug(parser): failure to convert nested elements

make/go.mk, pkg/parser/comment_test.go, pkg/parser/delimited_block_test.go, pkg/parser/document_processing.go, pkg/parser/document_processing_apply_substitutions.go, pkg/parser/generate.go, pkg/parser/labeled_list_test.go, pkg/parser/paragraph_test.go, pkg/parser/parser.go, pkg/parser/parser.peg, pkg/renderer/sgml/html5/paragraph_test.go, pkg/types/attributes.go, pkg/types/types.go
Support for one or more custom substitutions
Starting with Rawline elements which are parsed
and result in other elements. Subsequent substitutions
only apply on the StringElements.
At the end of the substitutions, the lines are preserved
Also, fix issues with single line comments which should not
start with spaces before the `//` marker
Fixes #597
=> feature(parser): custom subs on paragraphs

pkg/renderer/sgml/html5/delimited_block_test.go, pkg/renderer/sgml/html5/file_inclusion_test.go, pkg/renderer/sgml/html5/labeled_list_test.go, pkg/renderer/sgml/html5/paragraph_test.go, pkg/renderer/sgml/html5/quoted_string_test.go, pkg/renderer/sgml/html5/quoted_text_test.go, pkg/renderer/sgml/html5/string.go, pkg/renderer/sgml/html5/string_test.go, pkg/renderer/sgml/inline_elements.go, pkg/renderer/sgml/paragraph.go, pkg/renderer/sgml/xhtml5/delimited_block_test.go, pkg/renderer/sgml/xhtml5/file_inclusion_test.go, pkg/renderer/sgml/xhtml5/labeled_list_test.go, pkg/renderer/sgml/xhtml5/paragraph_test.go, pkg/renderer/sgml/xhtml5/quoted_string_test.go, pkg/renderer/sgml/xhtml5/quoted_text_test.go, test/fixtures/supported/basic.html, test/fixtures/supported/sample.html
With support for special characters in place, there is
no need to using the HTML "escape" func when
rendering StringElements.
Fixes #741
=> fix(renderer): do not 'HTML escape' string elements

pkg/renderer/sgml/html5/image.go, pkg/renderer/sgml/html5/image_test.go, pkg/renderer/sgml/image.go, pkg/renderer/sgml/xhtml5/image.go, pkg/renderer/sgml/xhtml5/image_test.go
They are used in libasciidoc's own README.adoc for badges and I wanted to use them in mine, without working around it with line noise:
```
perl -pe 's|\b(image:.*?\[.*?),\s*link=([^,]*?)(\])|+++<a href=$2>+++\n$1$3\n+++</a>+++|gx'
```
So that I'm not just bitching in issues. :) This was easy enough to add, even if tiring because of two super similar backends. Also notice that the templates are formatted differently.
=> feature(renderer): inline images deserve links, too

pkg/parser/document_processing_include_files_test.go, pkg/parser/document_test.go, pkg/parser/parser.go, pkg/parser/parser.peg
verify that document metadata are recognized when the
content starts with an empty line
Fixes #707
=> test(parser): verify document with leading empty line

pkg/parser/special_character_test.go, pkg/renderer/sgml/html5/special_character_test.go
Verifies that special characters are properly
handled in paragraphs and delimited blocks
Fixes #751
=> test(parser/renderer): verify special characters

pkg/parser/delimited_block_test.go, pkg/parser/document_processing_apply_substitutions.go, pkg/parser/parser.go, pkg/parser/parser.peg, pkg/renderer/sgml/html5/delimited_block_test.go, pkg/renderer/sgml/xhtml5/delimited_block_test.go
adding missing tests for custom subs on verse blocks at the
parser level, and for all subs at the rendering level
also, fix missing "InlineMacros" rule in the "VerseMacro" subs.
also, reorgnize tests so they all have the same structure,
in the parser and renderer pkgs.
=> feat(parser): support custom substitutions on delimited blocks

CHANGELOG.md
=> chore(project): missing version 'v0.5.1' in changelog header

cmd/libasciidoc/root_cmd.go, pkg/log/log_init.go, pkg/parser/document_processing_include_files_test.go, pkg/renderer/sgml/html5/file_inclusion_test.go, pkg/renderer/sgml/xhtml5/file_inclusion_test.go, testsupport/console_matcher.go, testsupport/log_init.go
unless the `-debug` flag was provided
this makes the output of the `ginkgo` command much easier
to read.
also, rename `console` to `logs` in tests.
Fixes #762
=> chore(test): avoid warning logs when running tests

pkg/parser/delimited_block_test.go, pkg/parser/document_processing_apply_substitutions.go, pkg/parser/literal_block_test.go, pkg/renderer/sgml/html5/literal_block_test.go, pkg/types/types.go
also, fixes the default substitutions
Fixes #770
=> feat(parser): support custom substitutions on literal blocks

pkg/parser/comment_test.go, pkg/parser/delimited_block_example_test.go, pkg/parser/delimited_block_listing_test.go, pkg/parser/delimited_block_literal_test.go, pkg/parser/delimited_block_passthrough_test.go, pkg/parser/delimited_block_quote_test.go, pkg/parser/delimited_block_source_test.go, pkg/parser/delimited_block_verse_test.go, pkg/parser/document_processing_test.go, pkg/parser/paragraph_test.go, pkg/parser/parser.go, pkg/parser/parser.peg, pkg/parser/section_test.go, pkg/renderer/sgml/delimited_block_admonition.go, pkg/renderer/sgml/delimited_block_example.go, pkg/renderer/sgml/delimited_block_listing.go, pkg/renderer/sgml/delimited_block_quote.go, pkg/renderer/sgml/delimited_block_source.go, pkg/renderer/sgml/delimited_block_verse.go, pkg/renderer/sgml/html5/delimited_block_example_test.go, pkg/renderer/sgml/html5/delimited_block_passthrough_test.go, pkg/renderer/sgml/paragraph.go, pkg/renderer/sgml/renderer.go, pkg/types/attributes.go, pkg/types/types.go
support paragraphs with the `[example]` attribute
also, rename `AttrKind` to `AttrBlockKind`
also, move some paragraph tests in delimited_block_* tests
Fixes #728
=> feat(parser/renderer): support example paragraphs

pkg/parser/document_processing_apply_custom_substitutions_test.go, pkg/parser/document_processing_apply_substitutions.go, pkg/parser/document_processing_apply_substitutions_test.go, pkg/types/types.go
support appending, prepending and removal of substitutions
Fixes #761
=> feat(parser): support incremental substitutions

pkg/parser/section_test.go, pkg/renderer/sgml/html5/section_test.go, pkg/types/attributes.go, pkg/types/types.go
=> feat(parser): support for 'idseparator' attribute

pkg/parser/mixed_lists_test.go, pkg/parser/parser.go, pkg/parser/parser.peg, pkg/parser/unordered_list_test.go, pkg/renderer/sgml/html5/unordered_list_test.go
only allow for `i`, `v`, `x`, `d`, `c` and `m` (and upper cases)
for roman numbering followed by a `)` for ordered list item with
roman numbering.
Just don't start a line with something like `mix)` unless it's
item number 1009 ;)
Fixes #747
=> fix(parser): check for letters in roman numbering of list item

pkg/parser/attributes_test.go, pkg/parser/document_processing_apply_substitutions.go, pkg/parser/image_test.go, pkg/parser/link_test.go, pkg/parser/paragraph_test.go, pkg/parser/parser.go, pkg/parser/parser.peg, pkg/parser/quoted_string_test.go, pkg/parser/quoted_text_test.go, pkg/renderer/sgml/html5/image_test.go, pkg/renderer/sgml/html5/link_test.go, pkg/renderer/sgml/image.go, pkg/renderer/sgml/link.go, pkg/types/attributes.go, pkg/types/types.go, pkg/types/types_test.go
Encode the link URL when it is used as the text (ie, no explicit text was provided for the link)
also, remove unused rules and unused funcs
also, do not resolve the image 'alt' attribute during parsing,
only during rendering
Fixes #745
=> fix(parser/renderer): encode URL in links when no text is provided

libasciidoc_test.go, pkg/configuration/configuration.go, pkg/renderer/sgml/elements.go, pkg/renderer/sgml/html5/document_details_test.go, pkg/renderer/sgml/html5/html5.go, pkg/renderer/sgml/html5/html5_test.go, pkg/renderer/sgml/html5/link_test.go, pkg/renderer/sgml/renderer.go, pkg/renderer/sgml/xhtml5/xhtml5.go, testsupport/metadata_matcher.go, testsupport/metadata_matcher_test.go, testsupport/render_html5.go, testsupport/render_html5_test.go
Sets the HTML title to `Untitled` when the document
did not have any section with level 0
Also, refactor a few vars and matchers (checking the
metadata result and not the rendered HTML content)
Fixes #627
=> feat(renderer): default HTML title

pkg/parser/attributes_test.go, pkg/parser/cross_reference_test.go, pkg/parser/delimited_block_example_test.go, pkg/parser/document_processing_apply_substitutions.go, pkg/parser/document_processing_apply_substitutions_test.go, pkg/parser/document_processing_footnotes.go, pkg/parser/image_test.go, pkg/parser/labeled_list_test.go, pkg/parser/ordered_list_test.go, pkg/parser/paragraph_test.go, pkg/parser/parser.go, pkg/parser/parser.peg, pkg/renderer/sgml/cross_reference.go, pkg/renderer/sgml/html5/paragraph.go, pkg/renderer/sgml/html5/paragraph_test.go, pkg/renderer/sgml/xhtml5/paragraph_test.go, pkg/types/attributes.go, pkg/types/types.go, pkg/types/types_test.go, pkg/types/types_utils.go
Support for standard "named" attributes (ie, with key/value, including
in single and double quotes), as well as on the `title` attribute. Also
works in other places such as image inline attributes.
Also, rename `doctitle` class to `title` for paragraph titles.
Also, removed more duplicate grammar rules related to attributes.
Fixes #604
=> feat(parser): support attribute substitution in element attributes

.github/workflows/ci-build.yml
Fixes a problem where the lint job would fail without
any explanation. Also, a good opportunity to update to the latest version.
Fixes #806 
=> chore(build): update golangci-lint-action to v2.3.0

pkg/parser/attributes_test.go, pkg/parser/paragraph_test.go, pkg/types/attributes.go
support the following syntax:
```
[.role1]
[.role2]
a paragraph
```
Fixes #602
=> fix: support multiple roles on blocks

pkg/parser/parser.go, pkg/parser/parser.peg, pkg/types/types.go
define the `start` attribute as optional for both `counter`
and `counter2` elements, and support alphanumeric or numeric
value in a separate rule.
Fixes #808
=> refactor(parser): simplify counter grammar rules

pkg/parser/link_test.go, pkg/renderer/sgml/html5/link.go, pkg/renderer/sgml/html5/link_test.go, pkg/renderer/sgml/link.go, pkg/types/attributes.go
=> feat(parser/renderer): support 'target' and 'role' attributes in link

make/profile.mk, pkg/parser/document_processing_insert_preamble.go, pkg/types/table.go, pkg/types/types_utils.go
improves memory consumption by ~1.6%, based on
`make profile` results compared to `master`
also, `make profile` now runs 10 iterations
=> refactor(project): make slices with capacity

pkg/parser/document_processing_apply_substitutions.go, pkg/parser/document_processing_filter_blocks.go, pkg/parser/document_processing_rearrange_lists.go, pkg/renderer/sgml/element_role.go, pkg/renderer/sgml/renderer.go, pkg/types/non_alphanumerics_replacement.go, pkg/types/types.go, pkg/types/types_utils.go
and use index to set value
also, replace remaining `bytes.Buffer` with `strings.Builder`
fixes #815
=> refactor(parser/renderer): allocate slices with expected capacity

pkg/parser/parser.go, pkg/parser/parser.peg
try to match `SimpleRawParagraph` rule as early as possible
in the delimited blocks content, as most of the time, content
is a paragraph anyways.
fixes #817
=> refactor(parser): reorganize delimted block content rules

pkg/parser/document_processing_apply_substitutions.go, pkg/parser/parser.peg, pkg/parser/quoted_string_test.go, pkg/types/types.go
Do not repeat parsing of attributes for each type of quoted text
Fixes #827
=> refactor(parser): parse quoted text attribute once

pkg/parser/cross_reference_test.go, pkg/parser/delimited_block_example_test.go, pkg/parser/delimited_block_literal_test.go, pkg/parser/delimited_block_markdown_quote_test.go, pkg/parser/delimited_block_quote_test.go, pkg/parser/delimited_block_sidebar_test.go, pkg/parser/delimited_block_verse_test.go, pkg/parser/document_processing_apply_custom_substitutions_test.go, pkg/parser/document_processing_rearrange_lists_test.go, pkg/parser/footnote_test.go, pkg/parser/icon_test.go, pkg/parser/index_terms_test.go, pkg/parser/inline_elements_test.go, pkg/parser/labeled_list_test.go, pkg/parser/link_test.go, pkg/parser/paragraph_test.go, pkg/parser/parser.peg, pkg/parser/passthrough_test.go, pkg/parser/quoted_string_test.go, pkg/parser/quoted_text_test.go, pkg/parser/section_test.go, pkg/parser/table_test.go, pkg/parser/unordered_list_test.go, pkg/renderer/sgml/quoted_text.go, pkg/types/non_alphanumeric_replacement_test.go, pkg/types/types.go, pkg/types/types_test.go
New interface for elements that can return their raw text representation
of as they were in the source document (supposedly)
For now, the following types implement this new interface:
- QuotedText
- QuotedString
- StringElement
- SpecialCharacter
- InlinePassthrough
- AttributeSubstitution
This is simpler than capturing the content that was parsed, because
in case where elements are embedded, we would need to process the
`ElementPlaceHolder`, which would add complexity.
Fixes #831
=> refactor(types): add func to return raw text

.github/workflows/ci-build.yml, make/lint.mk
applies to GH Workflow (using the golangci-lint-action) and
from CLI via `make lint`
Fixes #833
=> chore(build): use latest version of golangci-lint

make/clean.mk, make/go.mk
Compare the date of pkg/parser/parser.peg vs pkg/parser/parser.go.
If the latter is newer, then assume that the generated parser is up-to-date.
In doubt, provide a make clean goal to force the generation.
Fixes #840
=> chore(build): do not generate the parser if not needed

pkg/parser/link_test.go, pkg/renderer/sgml/html5/link_test.go
Add tests to verify that it now works, but was already fixed by #843
Closes #849
=> fix(parser): links with underscores

pkg/parser/attributes_test.go, pkg/parser/document_processing_apply_substitutions.go, pkg/parser/table_test.go, pkg/renderer/sgml/html5/table.go, pkg/renderer/sgml/html5/table_test.go, pkg/renderer/sgml/html5/templates.go, pkg/renderer/sgml/sgml_renderer.go, pkg/renderer/sgml/table.go, pkg/renderer/sgml/templates.go, pkg/renderer/sgml/xhtml5/table_test.go, pkg/types/attributes.go, pkg/types/types.go
Supports the shorthand (`%header%footer`) syntax and the explicit
one (`options="header,footer"`)
also, fixes a bug in column settings when multiplier is used
Fixes #861
=> feat(parser/renderer): support 'header' and 'footer' options in tables

pkg/parser/cross_reference_test.go, pkg/parser/delimited_block_literal_test.go, pkg/parser/delimited_block_source_test.go, pkg/parser/document_processing_aggregate.go, pkg/parser/paragraph_test.go, pkg/parser/table_test.go, pkg/renderer/sgml/cross_reference.go, pkg/renderer/sgml/html5/cross_reference_test.go, pkg/types/types.go
covers sections, tables, delimited blocks and paragraphs.
Fixes #863
=> fix(parser/renderer): support cross references in elements defined later

pkg/parser/cross_reference_test.go, pkg/parser/document_processing_aggregate.go, pkg/parser/q_a_list_test.go, pkg/parser/unordered_list_test.go, pkg/types/types.go
refactor the interface and visit/traverse the list elements
and delimited block elements to detect "nested" references
Updates #863
=> fix(parser): improve support for cross-references

pkg/parser/ordered_list_test.go, pkg/parser/unordered_list_test.go, pkg/renderer/sgml/html5/ordered_list_test.go, pkg/renderer/sgml/html5/table.go, pkg/renderer/sgml/html5/unordered_list_test.go, pkg/renderer/sgml/table.go, pkg/renderer/sgml/xhtml5/table.go, pkg/renderer/sgml/xhtml5/table_test.go
also, verifies that cross references work in list element continuations
(#837)
Fixes #867
Fixes #837
=> feat(renderer): support table ID

pkg/renderer/sgml/xhtml5/delimited_block_passthrough_test.go, pkg/renderer/sgml/xhtml5/paragraph_test.go, pkg/renderer/sgml/xhtml5/table.go, pkg/renderer/sgml/xhtml5/table_test.go
Also, fix a few other tests in the `xhtml5_test` package which were
using the `HTML5` renderer intead of the `XHTML5` one :/
Fixes #870
=> fix(renderer): missing footer when rendering with XHTML5 backend

libasciidoc_test.go, pkg/parser/delimited_block_listing_test.go, pkg/parser/document_processing_include_files_test.go, pkg/renderer/sgml/html5/file_inclusion_test.go, pkg/renderer/sgml/xhtml5/file_inclusion_test.go, testsupport/console_matcher.go, testsupport/console_matcher_test.go
make sure that a test can call multiple times
assertions such as `ContainJSONLog` on a given
console output.
Also, provide the alternative `ContainJSONLogWithOffset func
to assert lines with `start_offset` and `end_offset` fields.
=> refactor(test): support multiple assertions

pkg/parser/document_preprocessing_include_files.go, pkg/parser/document_processing_parse_fragments.go, pkg/parser/parser.peg, pkg/parser/parser_ext.go
no need for checking if/what kind of delimited block is being parsed.
=> refactor(parser): remove unnecessary grammar rules

pkg/parser/document_preprocessing_include_files.go, pkg/parser/document_preprocessing_include_files_test.go, pkg/parser/document_processing_apply_substitutions.go, pkg/parser/parser.peg, pkg/parser/parser_ext.go
remove unneeded conditions and simplify support for inclusion
of non-asciidoc files.
=> refactor(parser): simplify file inclusion rule

pkg/renderer/sgml/html5/document_details_test.go, pkg/renderer/sgml/html5/html5.go, pkg/renderer/sgml/renderer.go, pkg/types/attributes.go
appears in HTML document as a `<meta name="description" content="...">`
tag
fixes #892
=> feat(renderer): support for description metadata

pkg/parser/document_header_test.go, pkg/parser/parser.peg, pkg/renderer/sgml/html5/document_details_test.go
using recursive grammar rule to parse subsequent lines when
line ends with the `\` continuation character.
fixes #891
=> feat(parser): support soft-wrapping of attribute values

pkg/parser/document_preprocessing.go, pkg/parser/document_preprocessing_conditionals_test.go, pkg/parser/parser.peg, pkg/types/types.go
=> feat(parser): support for single-line ifdef/ifndef directives

pkg/parser/document_preprocessing_conditionals_test.go, pkg/parser/parser.peg
name is parsed but no check is done with regards to current ifdef/ifnded
directives.
fixes #898
=> feat(parser): support attribute name in 'endif' directive

pkg/parser/document_processing_apply_substitutions.go, pkg/parser/link_test.go, pkg/parser/parser.peg, pkg/types/attributes.go, pkg/types/types.go
inline ID is treated as an anchor instead of a standalone attribute
fixes #901
=> feat(parser): support for inline anchors

pkg/parser/attributes_test.go, pkg/parser/document_processing_filter_elements_test.go, pkg/parser/icon_test.go, pkg/parser/mixed_lists_test.go, pkg/parser/parser.peg, pkg/parser/section_test.go, pkg/renderer/sgml/html5/link.go, pkg/renderer/sgml/html5/section_test.go, pkg/renderer/sgml/link.go, pkg/types/non_alphanumerics_replacement.go, pkg/types/types.go
clarify the use of inline anchors vs custom IDs
fixes #903
=> fix(parser/renderer): inline anchors and custom ID in sections

pkg/renderer/sgml/cross_reference.go, pkg/renderer/sgml/html5/cross_reference_test.go
compute the default label from the xref's location
fixes #905
=> fix(renderer): support empty label in cross-references

pkg/parser/link_test.go, pkg/renderer/sgml/html5/link_test.go
add tests, was already fixed in #912
closes #911
=> fix: ignore punctuation at the end of links

libasciidoc.go, pkg/parser/document_preprocessing_conditionals_test.go, testsupport/preparse_document.go
when rendering in HTML or XHTML, set the 'basebackend-html' attribute so
the content of 'ifdef::basebackend-html' directives can be included in
the document to render.
Fixes #925
=> feat(parser): default basebackend

libasciidoc_test.go, pkg/parser/attribute_substitution_test.go, pkg/parser/document_fragment_processing_test.go, pkg/parser/document_header_test.go, pkg/parser/document_processing_aggregate_test.go, pkg/parser/table_of_contents_test.go, pkg/renderer/context.go, pkg/renderer/sgml/elements.go, pkg/renderer/sgml/html5/file_inclusion_test.go, pkg/renderer/sgml/html5/quoted_string_test.go, pkg/renderer/sgml/inline_elements.go, pkg/renderer/sgml/renderer.go, pkg/renderer/sgml/string.go, pkg/renderer/sgml/table_of_contents.go, pkg/renderer/sgml/xhtml5/file_inclusion_test.go, pkg/types/types.go, testsupport/document_metadata_test.go
also: remove `renderer.Context.TableOfContents`
BREAKING CHANGES:
- `types.Metadata.TableOfContents` is `*types.TableOfContents` (pointer)
- `types.TableOfContents.MaxDepth` field exported
Fixes https://github.com/bytesparadise/libasciidoc/issues/937
=> fix(renderer): smart quotes in table of contents

libasciidoc_bench_test.go, libasciidoc_test.go, pkg/parser/attribute_substitution_test.go, pkg/parser/comment_test.go, pkg/parser/context.go, pkg/parser/cross_reference_test.go, pkg/parser/document_fragment_processing_test.go, pkg/parser/document_header_test.go, pkg/parser/document_preprocessing_include_files_test.go, pkg/parser/document_processing_aggregate.go, pkg/parser/document_processing_aggregate_test.go, pkg/parser/document_test.go, pkg/parser/footnote_test.go, pkg/parser/icon_test.go, pkg/parser/link_test.go, pkg/parser/quoted_string_test.go, pkg/parser/section_test.go, pkg/renderer/sgml/html5/file_inclusion_test.go, pkg/renderer/sgml/renderer.go, pkg/renderer/sgml/table_of_contents.go, pkg/renderer/sgml/xhtml5/file_inclusion_test.go, pkg/types/types.go
the `types.Metadata` value returned by the call to `libasciidoc.Convert(...)`
contains a TableOfContents (when non-empty), even if the ToC is not
rendered.
Fixes #939
=> feat(parser/renderer): always include non-empty ToC in metadata

pkg/types/types.go
assume header (if it exists) is in first position of the document
elements
=> refactor(types): simplify access to document header

pkg/renderer/sgml/elements.go, pkg/renderer/sgml/html5/delimited_block_source_test.go, pkg/renderer/sgml/html5/string.go, pkg/renderer/sgml/html5/templates.go, pkg/renderer/sgml/sgml_renderer.go, pkg/renderer/sgml/string.go, pkg/renderer/sgml/templates.go
do not replace with HTML entities, which caused troubles
with syntax highlighting.
also, remove StringElement template (no real value)
Fixes #962
=> fix(renderer): non-ascii characters in listing content

README.adoc
If run as-is, the current symlink command will create a broken link:
```
$ sudo ln -s  ./bin/libasciidoc /usr/bin/libasciidoc
$ file /usr/bin/libasciidoc
/usr/bin/libasciidoc: broken symbolic link to ./bin/libasciidoc
```
This command works and produces a working absolute link:
```console
$ sudo ln -s "$PWD/bin/libasciidoc" /usr/bin/libasciidoc
```
=> Fallback symlink command doesn't work

.github/workflows/ci-bench.yml, make/bench.mk, make/git.mk
compares bench results against `master` and `v0.7.0`
Fixes #987
=> test(bench): run bench-diff on CI

pkg/parser/link_test.go, pkg/renderer/sgml/html5/link.go, pkg/renderer/sgml/html5/link_test.go, pkg/renderer/sgml/link.go, pkg/types/types.go
=> feat(renderer): support caret in links

pkg/parser/parser.peg, pkg/parser/parser_ext.go, pkg/parser/symbol_test.go, pkg/renderer/sgml/html5/symbol_test.go, pkg/renderer/sgml/symbol.go, pkg/types/types_utils.go
=> feat(parser/renderer): support m-dashes and arrows

.github/workflows/ci-build.yml, .gitignore, go.mod, go.sum, make/test.mk, tools.go
=> chore(project): remove usage of gover

.github/workflows/ci-build.yml
=> chore(project): run golangci-lint-action on Go 1.17 only

pkg/parser/parser.peg
=> refactor(parser): simplify the 'InlineElement' rule

pkg/parser/parser.peg, pkg/types/types.go
use 'ListElementContent' instead
=> refactor(parser): delete 'CalloutListElementContent' rule

pkg/parser/parser.peg
no need to parse 'Quote' at this stage (will be done later)
=> refactor(parser): simplify AttributeValueContent rules

.golangci.yml
=> chore(project): increase linter timeout to 10m

pkg/parser/delimited_block_listing_test.go, pkg/parser/delimited_block_literal_test.go, pkg/parser/parser.peg, pkg/parser/section_test.go
do not include raw content within paragraph.
Fixes #1008
=> fix(parser): delimited block immediately after paragraph

pkg/parser/document_processing_apply_substitutions.go, pkg/parser/document_processing_apply_substitutions_test.go
only apply attribute substitutions
=> refactor(parser): do not reparse image 'alt' attribute

pkg/renderer/sgml/html5/delimited_block_open_test.go, pkg/renderer/sgml/html5/image_test.go, pkg/renderer/sgml/html5/table_test.go, pkg/renderer/sgml/image.go
replace underscores and hyphens with spaces
Fixes #1019
=> fix(renderer): image alt without separators

pkg/parser/table_test.go, pkg/renderer/sgml/html5/table_test.go
verifies that the 'frame' and 'grid' attributes are supported
Fixes #1016
=> test(parser/renderer): custom table borders

README.adoc, pkg/renderer/sgml/delimited_block_source.go, pkg/renderer/sgml/html5/delimited_block_source_test.go, pkg/types/attributes.go
keeping default to 'tok-' for backward compatibility (and with Asciidoctor)
Fixes #971
=> feat(renderer): custom prefix for syntax hightlighting classes

pkg/parser/context.go, pkg/parser/document_preprocessing.go, pkg/parser/document_processing_apply_substitutions.go, pkg/parser/document_processing_parse_fragments.go, testsupport/parse_document_fragment_groups.go
finally addressing this long-time TODO comment ;)
=> refactor(parser): unexport 'opts' field in Context type

pkg/parser/document_processing_apply_substitutions.go, pkg/parser/document_processing_arrange_lists.go, pkg/parser/document_processing_parse_fragments.go, pkg/parser/parser.peg, pkg/types/types.go
also, rename `ListElementContinuation`
to `ListContinuation`
=> refactor(parser): merge 'AdmonitionParagraph' and 'Paragraph' rules

pkg/parser/attributes_test.go, pkg/parser/comment_test.go, pkg/parser/delimited_block_literal_test.go, pkg/parser/delimited_block_passthrough_test.go, pkg/parser/document_preprocessing.go, pkg/parser/document_processing_apply_substitutions.go, pkg/parser/document_processing_parse_fragments.go, pkg/parser/mixed_lists_test.go, pkg/parser/ordered_list_test.go, pkg/parser/parser.peg, pkg/parser/parser_ext.go, pkg/parser/parser_ext_test.go, pkg/parser/q_a_list_test.go, pkg/parser/section_test.go, pkg/parser/unordered_list_test.go, pkg/renderer/sgml/delimited_block_example.go, pkg/renderer/sgml/literal_blocks.go, pkg/renderer/sgml/paragraph.go, pkg/types/attributes.go, pkg/types/types.go, test/compat/demo.adoc
Also, removed obsolete constants for attributes.
Also, remove support for _implicit_ continuation of
literal paragraph: `+` character is required.
=> refactor(parser): merge 'LiteralParagraph' and 'Paragraph' rules

pkg/parser/labeled_list_test.go, pkg/parser/parser.peg, pkg/types/types.go
=> refactor(parser): simplify grammar rules for list elements

pkg/parser/parser.peg, pkg/parser/quoted_text_test.go, pkg/types/attributes.go
parse attributes only once for escaped and unescaped text
store attributes in current state
=> refactor(parser): simplify QuotedText rule

pkg/parser/parser.peg
(hopefully) improves readability of othe rules
'AnyChars' can have zero or more characters (except CRLF)
'ManyChars' must have 1 or more characters (excetp CRLF)
=> refactor(parser): AnyChar,AnyChars and ManyChars grammar rules

pkg/parser/document_processing_aggregate.go, pkg/parser/document_processing_insert_preamble_test.go, pkg/parser/document_processing_parse_fragments.go, pkg/parser/parser.peg, pkg/parser/section_test.go, pkg/renderer/context.go, pkg/renderer/sgml/html5/section_test.go, pkg/renderer/sgml/renderer.go, pkg/types/section_numbering_test.go, pkg/types/types.go, pkg/validator/validator.go
Only disable the 'DocumentHeader' rule if the element is not a FrontMatter (or a blankline)
Fixes #1041
=> fix(parser): detect DocumentHeader when doc has FrontMatter

pkg/parser/attribute_substitution_test.go, pkg/parser/parser.peg, pkg/types/types.go
also, add test on attribute refs in links
=> refactor(types): rename func to init AttributeReferences

pkg/parser/cross_reference_test.go, pkg/parser/document_processing_aggregate.go, pkg/renderer/sgml/cross_reference.go, pkg/renderer/sgml/elements.go, pkg/renderer/sgml/html5/cross_reference_test.go, pkg/types/non_alphanumerics_replacement.go, pkg/types/types.go, pkg/types/types_test.go
reference with section title instead of ID
Fixes #1044
=> feat(parser): support natural cross references

pkg/parser/cross_reference_test.go, pkg/parser/delimited_block_open_test.go, pkg/parser/table_test.go, pkg/renderer/sgml/html5/cross_reference_test.go, pkg/types/types.go
=> feat(parser): support cross references to images within tables

pkg/parser/section_test.go, pkg/renderer/sgml/html5/cross_reference_test.go, pkg/types/types.go, pkg/types/types_utils.go, pkg/types/types_utils_test.go
=> fix(parser/renderer): trim trailing spaces in section title

cmd/libasciidoc/root_cmd.go, go.mod, libasciidoc.go, libasciidoc_bench_test.go, pkg/parser/document_header_test.go, pkg/parser/document_processing.go, pkg/parser/document_processing_apply_substitutions.go, pkg/parser/document_substitutions.go, pkg/parser/document_substitutions_test.go, pkg/parser/link_test.go, pkg/parser/paragraph_test.go, pkg/parser/parser.peg, pkg/parser/symbol_test.go
ie, if attribute substitution occurred
=> refactor(parser): reparse content if needed only

pkg/parser/parser.peg
=> refactor(parser): remove unnecessary 'RawApostrophe' grammar rule

pkg/parser/attributes_test.go, pkg/parser/context.go, pkg/parser/cross_reference_test.go, pkg/parser/delimited_block_verse_test.go, pkg/parser/document_fragment_processing_test.go, pkg/parser/document_processing_apply_substitutions.go, pkg/parser/document_processing_parse_fragments.go, pkg/parser/document_substitutions.go, pkg/parser/generate.go, pkg/parser/link_test.go, pkg/parser/parser.peg, pkg/parser/parser_ext.go, pkg/parser/quoted_string_test.go, pkg/parser/quoted_text_test.go, pkg/parser/section_test.go, pkg/parser/symbol_test.go, pkg/parser/unordered_list_test.go, pkg/renderer/sgml/html5/quoted_text_test.go, pkg/renderer/sgml/render_plain_text.go, pkg/renderer/sgml/symbol.go, pkg/renderer/sgml/xhtml5/quoted_text_test.go, pkg/types/non_alphanumeric_replacement_test.go, pkg/types/non_alphanumerics_replacement.go, pkg/types/types.go
track last element in a group to compare with its latest character
when needed (ie, to check if a rule can apply or not)
also:
- simplify the `InlineWord` rule
- use `pN` as a class matcher for numbers
- refactor the `Symbol` type
Fixes #1077
=> refactor(parser): simplify QuotedText rules

pkg/parser/quoted_text_test.go, pkg/renderer/sgml/html5/quoted_text_test.go
verifies that `*a_b* _c_` is parsed and renderer as expected
bug itself ws fixed in eecd0bb
Fixes #1078
=> test(parser/renderer): verify quoted text case

go.mod, testsupport/log_init.go
change the `-debug` (bool) arg to
`--loglevel=[debug|info|warn|error]` (string) for more flexibility
in the log level setting during test execution
=> test(project): loglevel arg

testsupport/log_init.go
=> test(project): restore default log level to 'error'

pkg/parser/table_of_contents_test.go, pkg/renderer/sgml/html5/footnote_reference_test.go, pkg/renderer/sgml/html5/table_of_contents_test.go, pkg/renderer/sgml/table_of_contents.go
=> feat(renderer): support inline formatting in table of contents

README.adoc
explain how to generate a CSS with custom prefixes using the Chroma CLI
Fixes #971
=> chore(docs): update README related to Chroma prefixes

pkg/renderer/sgml/sgml.go
This function is necessary to allow custom backends to only use the basename of an image in cases where images are stored as attachments.
```
blockImageTmpl = `<image ><attachment filename="{{ basename .Src }}" /></image>`
```
=> Add basename function to sgml FuncMap
